export const campaignSortAccessors = {
  projectName: (r) => r.projectName,
  projectNameLabel: 'Campaign',
  status: (r) => r.status,
  statusLabel: 'Stage',
  targetCompaniesCount: (r) => r.targetCompaniesCount || 0,
  targetCompaniesCountLabel: 'Companies found',
  companiesReached: (r) => r.companiesReached || 0,
  companiesReachedLabel: 'Companies reached',
  pocsFound: (r) => r.pocsFound || 0,
  pocsFoundLabel: 'POCs found',
  pocsEmailed: (r) => r.pocsEmailed || 0,
  pocsEmailedLabel: 'POCs emailed',
  pocsResponded: (r) => r.pocsResponded || 0,
  pocsRespondedLabel: 'POCs responded',
  activeQueues: (r) => r.activeQueues || 0,
  activeQueuesLabel: 'In queue',
};

export const companySortAccessors = {
  companyName: (r) => r.companyName,
  companyNameLabel: 'Company',
  domain: (r) => r.domain,
  domainLabel: 'Domain',
  location: (r) => `${r.city || ''} ${r.country || ''}`.trim(),
  locationLabel: 'Location',
  pocCount: (r) => r.pocCount || 0,
  pocCountLabel: 'Contacts',
  campaigns: (r) => (r.campaignNames || []).join(', '),
  campaignsLabel: 'Campaigns',
  globalStatus: (r) => r.globalStatus,
  globalStatusLabel: 'Status',
};

export const leadSortAccessors = {
  name: (r) => r.name,
  nameLabel: 'Contact',
  companyName: (r) => r.companyName,
  companyNameLabel: 'Company',
  email: (r) => r.email,
  emailLabel: 'Email',
  campaignName: (r) => r.campaignName,
  campaignNameLabel: 'Campaign',
  designation: (r) => r.designation,
  designationLabel: 'Role',
  pocStatus: (r) => r.pocQualification?.status,
  pocStatusLabel: 'POC fit',
  deliveryStatus: (r) => r.deliveryStatus,
  deliveryStatusLabel: 'Email status',
  emailApollo: (r) => r.emailApollo,
  emailApolloLabel: 'Apollo',
  emailHunter: (r) => r.emailHunter,
  emailHunterLabel: 'Hunter',
  emailLusha: (r) => r.emailLusha,
  emailLushaLabel: 'Lusha',
  outreachEmail: (r) => r.outreachEmail,
  outreachEmailLabel: 'Outreach',
  hasResponded: (r) => (r.hasResponded ? 1 : 0),
  hasRespondedLabel: 'Response',
  respondedAt: (r) => r.respondedAt,
  respondedAtLabel: 'Response date',
  outcome: (r) => r.outcome,
  outcomeLabel: 'Outcome',
};

export const relationshipSortAccessors = {
  name: (r) => r.name,
  nameLabel: 'Contact',
  companyName: (r) => r.companyName,
  companyNameLabel: 'Company',
  lastInteraction: (r) => r.lastInteractionAt,
  lastInteractionLabel: 'Last interaction',
  relationshipStatus: (r) => r.relationshipProfile?.status,
  relationshipStatusLabel: 'Relationship',
  owner: (r) => r.relationshipProfile?.owner,
  ownerLabel: 'Owner',
  nextFollowUp: (r) => r.relationshipProfile?.nextFollowUpAt,
  nextFollowUpLabel: 'Follow-up',
  notes: (r) => r.relationshipProfile?.reminderNotes,
  notesLabel: 'Notes',
};

export const opportunitySortAccessors = {
  name: (r) => r.name,
  nameLabel: 'Opportunity',
  company: (r) => r.companyId?.companyName,
  companyLabel: 'Company',
  stage: (r) => r.stage,
  stageLabel: 'Stage',
  valueAed: (r) => r.valueAed || 0,
  valueAedLabel: 'Value',
  owner: (r) => r.owner,
  ownerLabel: 'Owner',
  createdAt: (r) => r.createdAt || r.expectedCloseDate,
  createdAtLabel: 'Opened',
  updatedAt: (r) => r.updatedAt,
  updatedAtLabel: 'Updated',
};

export const taskSortAccessors = {
  title: (r) => r.title,
  titleLabel: 'Task',
  dueAt: (r) => r.dueAt,
  dueAtLabel: 'Due',
  campaign: (r) => r.campaignId?.projectName,
  campaignLabel: 'Project',
  opportunity: (r) => r.opportunityId?.name,
  opportunityLabel: 'Opportunity',
  company: (r) => r.companyId?.companyName,
  companyLabel: 'Company',
  owner: (r) => r.owner,
  ownerLabel: 'Owner',
  priority: (r) => r.priority,
  priorityLabel: 'Priority',
  status: (r) => r.status,
  statusLabel: 'Status',
};

export const campaignCompanySortAccessors = {
  companyName: (r) => r.companyName,
  companyNameLabel: 'Company',
  domain: (r) => r.domain,
  domainLabel: 'Domain',
  location: (r) => `${r.city || ''} ${r.country || ''}`.trim(),
  locationLabel: 'Location',
  pocCount: (r) => r.pocCount || 0,
  pocCountLabel: 'Contacts',
  hasResponded: (r) => (r.hasResponded ? 1 : 0),
  hasRespondedLabel: 'Response',
};

export const sequenceSortAccessors = {
  name: (r) => r.name,
  nameLabel: 'Sequence',
  campaign: (r) => r.campaign?.projectName,
  campaignLabel: 'Campaign',
  steps: (r) => r.steps?.length || 0,
  stepsLabel: 'Steps',
  status: (r) => (r.isActive ? 'Live' : 'Draft'),
  statusLabel: 'Status',
  enrolled: (r) => r.stats?.enrolled || 0,
  enrolledLabel: 'Enrolled',
  queue: (r) => r.stats?.pending || 0,
  queueLabel: 'Queue',
  updatedAt: (r) => r.updatedAt,
  updatedAtLabel: 'Updated',
};

export const revenueSortAccessors = {
  project: (r) => r.campaignId?.projectName,
  projectLabel: 'Project',
  company: (r) => r.companyId?.companyName,
  companyLabel: 'Company',
  description: (r) => r.description,
  descriptionLabel: 'Description',
  amount: (r) => r.amount || 0,
  amountLabel: 'Amount',
  date: (r) => r.closedAt || r.createdAt,
  dateLabel: 'Date',
};

export const campaignRoiSortAccessors = {
  projectName: (r) => r.projectName,
  projectNameLabel: 'Campaign',
  milestone: (r) => r.milestone,
  milestoneLabel: 'Milestone',
  totalCost: (r) => r.totalCost || 0,
  totalCostLabel: 'Total cost',
  revenueWon: (r) => r.revenueWon || 0,
  revenueWonLabel: 'Revenue',
  roi: (r) => r.roi || 0,
  roiLabel: 'ROI',
  status: (r) => r.status,
  statusLabel: 'Status',
};

export const userSortAccessors = {
  displayName: (r) => r.displayName,
  displayNameLabel: 'Team member',
  email: (r) => r.email,
  emailLabel: 'Email',
  role: (r) => r.role,
  roleLabel: 'Role',
  isActive: (r) => (r.isActive ? 1 : 0),
  isActiveLabel: 'Status',
  lastLoginAt: (r) => r.lastLoginAt,
  lastLoginAtLabel: 'Last login',
};
