import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, BarChart3, CalendarClock, Camera, CheckCircle2, CircleDollarSign, Clock3, PackageSearch, RefreshCw, ShieldAlert, Wrench } from 'lucide-react';
import { crmApiFetch } from '../crmApi.js';
import { Alert, Badge, EmptyState, LoadingState, PageHeader, PageSection, PageShell, StatCard } from '../components/ui/primitives.jsx';

function dateInput(date) { return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10); }
function money(value) { return new Intl.NumberFormat('en-AE', { style: 'currency', currency: 'AED', maximumFractionDigits: 0 }).format(Number(value || 0)); }
function when(value) { return value ? new Date(value).toLocaleString('en-AE', { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' }) : '—'; }
function JobLink({ item, onOpen, detail }) { return <button className="text-left hover:text-brand" onClick={() => onOpen(item.jobId || item.id)}><strong className="text-xs">{item.jobTitle || item.title}</strong>{detail && <p className="mt-1 text-2xs text-neutral-500">{detail}</p>}</button>; }

function ExceptionList({ title, description, items, icon: Icon, render, onOpen, total }) {
  const count = total ?? items.length;
  return <section className="rounded-xl border border-neutral-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-brand" /><h3 className="text-sm font-semibold">{title}</h3></div><p className="mt-1 text-2xs text-neutral-500">{description}</p></div><Badge tone={count ? 'warning' : 'success'}>{count}</Badge></div><div className="mt-3 space-y-2">{items.slice(0, 8).map((item) => <div key={`${title}-${item.id}`} className="rounded-lg border border-neutral-100 p-2.5">{render(item, onOpen)}</div>)}{!items.length && <p className="py-4 text-center text-xs text-emerald-700">No current exceptions.</p>}</div></section>;
}

export default function OperationsReportsPage() {
  const navigate = useNavigate(); const today = new Date(); const [from, setFrom] = useState(dateInput(new Date(today.getFullYear() - 1, today.getMonth(), today.getDate()))); const [to, setTo] = useState(dateInput(today)); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [settlement, setSettlement] = useState(null);
  const load = useCallback(async () => { setLoading(true); try { setError(''); const params = new URLSearchParams({ from, to }); const [report, queues] = await Promise.all([crmApiFetch(`/api/admin/reports/operations?${params}`), crmApiFetch('/api/admin/sales/settlement-queues').catch(() => null)]); setData(report); setSettlement(queues); } catch (err) { setError(err.message || 'Failed to load operational reports.'); } finally { setLoading(false); } }, [from, to]); useEffect(() => { load(); }, [load]);
  const openJob = (id) => navigate(`/admin/crm/ongoing-jobs?recordType=ongoing_job&recordId=${id}`);
  const photoPreparation = useMemo(() => (data?.jobs || []).filter((item) => ['Ready','Installation','Waiting Balance Payment','Job Done'].includes(item.stage) && !item.finalPhotoCount), [data]);
  if (loading && !data) return <PageShell><LoadingState label="Building operational report from live records…" /></PageShell>;
  const s = data?.summary || {};
  return <PageShell className="max-w-none"><PageHeader actions={<div className="flex flex-wrap items-end gap-2"><label className="text-2xs text-neutral-500">From<input type="date" className="crm-input mt-1 w-38" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label className="text-2xs text-neutral-500">To<input type="date" className="crm-input mt-1 w-38" value={to} onChange={(e) => setTo(e.target.value)} /></label><button className="crm-btn-secondary" onClick={load} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div>} /><PageSection>{error && <Alert>{error}</Alert>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard compact label="Active Jobs" value={s.activeJobs} icon={Wrench} /><StatCard compact label="Jobs Done in period" value={s.doneJobs} icon={CheckCircle2} /><StatCard compact label="Blocked activities" value={s.blockedActivities} icon={ShieldAlert} tone={s.blockedActivities ? 'warning' : 'neutral'} /><StatCard compact label="Installations next 7 days" value={s.upcomingInstallations} icon={CalendarClock} /><StatCard compact label="Average data coverage" value={`${s.averageCoverage || 0}%`} icon={BarChart3} tone={(s.averageCoverage || 0) < 70 ? 'warning' : 'success'} /></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><StatCard compact label="Approved Job revenue measured" value={money(s.approvedRevenue)} helpText="Latest approved quotation for Jobs completed during this period." icon={CircleDollarSign} /><StatCard compact label="Actual supplier costs" value={money(s.supplierActualCost)} helpText="From supplier commitments with recorded actual amounts." icon={PackageSearch} /><StatCard compact label="Actual labour costs" value={money(s.laborActualCost)} helpText="From completed project time and resource hourly cost." icon={Clock3} /><StatCard compact label="Actual material costs" value={money(s.materialActualCost)} helpText="From priced inventory consumption, damage and loss movements linked to Jobs." icon={PackageSearch} /><StatCard compact label="Other actual costs" value={money(s.otherActualCost)} helpText="Permits, transport, rentals, petty cash and other explicitly recorded Job costs." icon={CircleDollarSign} /><StatCard compact label="Confirmed actual margin" value={money(s.confirmedMargin)} helpText={`${s.trustworthyMarginJobs || 0} completed Jobs have been explicitly cost-confirmed.`} icon={BarChart3} tone={s.confirmedMargin < 0 ? 'warning' : 'success'} /></div>
    <Alert tone="info" className="mt-4">Margin includes only completed Jobs whose costing was explicitly confirmed. Unconfirmed Jobs remain excluded rather than being reported as zero-cost work.</Alert>
    <div className="mt-5 grid gap-4 xl:grid-cols-3"><ExceptionList title="Production blockers" description="Activities explicitly blocked or carrying an unresolved blocker." items={data.exceptions.blockedActivities} icon={ShieldAlert} onOpen={openJob} render={(item, open) => <JobLink item={item} onOpen={open} detail={`${item.title} · ${item.ownerName || 'Unassigned'}${item.blocker ? ` · ${item.blocker}` : ''}`} />} /><ExceptionList title="Overdue supplier delivery" description="Committed supplier work past its expected delivery." items={data.exceptions.overdueSuppliers} icon={PackageSearch} onOpen={openJob} render={(item, open) => <JobLink item={item} onOpen={open} detail={`${item.supplierName} · ${item.description} · due ${when(item.expectedDeliveryAt)}`} />} /><ExceptionList title="Overdue snags" description="Open closeout corrections past their due date." items={data.exceptions.overdueSnags} icon={AlertTriangle} onOpen={openJob} render={(item, open) => <JobLink item={item} onOpen={open} detail={`${item.title} · ${item.severity} · ${item.ownerName || 'Unassigned'}`} />} /><ExceptionList title="Upcoming installations" description="Installation activities starting during the next seven days." items={data.exceptions.upcomingInstallations} icon={CalendarClock} onOpen={openJob} render={(item, open) => <JobLink item={item} onOpen={open} detail={`${item.title} · ${when(item.plannedStart)} · ${item.ownerName || 'Unassigned'}`} />} /><ExceptionList title="Long-running timers" description="Mobile timers left running for more than twelve hours." items={data.exceptions.longTimers} icon={Clock3} onOpen={openJob} render={(item, open) => <JobLink item={item} onOpen={open} detail={`${item.resourceName} · started ${when(item.startedAt)}`} />} /><ExceptionList title="Final photos to prepare" description="Jobs at or beyond readiness without final delivery photography. Historical Done Jobs are shown as backlog, not retroactively blocked." items={photoPreparation} icon={Camera} onOpen={openJob} render={(item, open) => <JobLink item={{ ...item, jobId: item.id, jobTitle: item.title }} onOpen={open} detail={`${item.stage} · ${item.owner || 'Unassigned'}`} />} /><ExceptionList title="Inventory warnings" description="Items at or below their configured reorder level." items={data.exceptions.lowStock} icon={AlertTriangle} onOpen={() => navigate('/admin/crm/inventory')} render={(item) => <button className="text-left" onClick={() => navigate('/admin/crm/inventory')}><strong className="text-xs">{item.name}</strong><p className="mt-1 text-2xs text-neutral-500">{item.sku} · balance {item.quantity} · warning level {item.reorderLevel}</p></button>} /></div>
    {settlement && <div className="mt-5 grid gap-4 xl:grid-cols-3">
      <ExceptionList title="Delivered but unpaid" description="Physically handed over while money remains outstanding. Works from Zoho figures where synced, otherwise from the recorded operational milestone." items={settlement.deliveredButUnpaid} total={settlement.totals?.deliveredButUnpaid} icon={CircleDollarSign} onOpen={openJob} render={(item, open) => <JobLink item={{ ...item, jobId: item.ongoingJobId, jobTitle: item.title }} onOpen={open} detail={`${item.settlementSource === 'zoho_sync' ? money(item.outstanding) + ' outstanding' : 'Operational milestone (manual)'} · delivered ${when(item.physicallyDeliveredAt)}`} />} />
      <ExceptionList title="Overdue payment" description="Issued Zoho invoices past their due date. Stays empty until the Zoho sync exists, because a manual milestone carries no due date." items={settlement.overdue} total={settlement.totals?.overdue} icon={AlertTriangle} onOpen={openJob} render={(item, open) => <JobLink item={{ ...item, jobId: item.ongoingJobId, jobTitle: item.title }} onOpen={open} detail={`${money(item.outstanding)} · ${item.daysOverdue} days overdue`} />} />
      <ExceptionList title="Settlement not recorded" description="Nobody has recorded a payment position. Shown so silence stays visible instead of looking like nothing is owed." items={settlement.unrecorded} total={settlement.totals?.unrecorded} icon={ShieldAlert} onOpen={openJob} render={(item, open) => <JobLink item={{ ...item, jobId: item.ongoingJobId, jobTitle: item.title }} onOpen={open} detail={`${item.jobNumber || 'No number'} · ${item.physicalDeliveryState === 'delivered' ? 'Delivered' : 'Not delivered'}`} />} />
    </div>}
    <section className="mt-5 overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="p-4"><h3 className="text-sm font-semibold">Job operational coverage</h3><p className="mt-1 text-xs text-neutral-500">Coverage indicates whether source records exist. It is not a subjective performance score.</p></div><div className="overflow-x-auto"><table className="crm-table w-full text-xs"><thead><tr className="crm-table-head"><th>Job</th><th>Stage</th><th>Coverage</th><th>Scope</th><th>Plan</th><th>Release</th><th>Supplier actuals</th><th>Time</th><th>Final photos</th><th>Costing</th><th>Learning</th></tr></thead><tbody>{data.jobs.map((item) => <tr key={item.id} className="cursor-pointer" onClick={() => openJob(item.id)}><td><strong>{item.title}</strong><p className="text-2xs text-neutral-400">{item.jobNumber || 'No number'} · {item.owner || 'Unassigned'}</p></td><td><Badge tone={item.stage === 'Job Done' ? 'success' : 'info'}>{item.stage}</Badge></td><td><strong className={item.coveragePercent < 70 ? 'text-amber-700' : 'text-emerald-700'}>{item.coveragePercent}%</strong></td><td>{item.scopeCount || <span className="text-neutral-400">Missing</span>}</td><td>{item.activityCount || <span className="text-neutral-400">Missing</span>}</td><td>{item.hasProductionRelease ? 'Yes' : <span className="text-neutral-400">Missing</span>}</td><td>{item.supplierCommitments ? (item.supplierCostComplete ? 'Complete' : `${item.supplierActualKnown}/${item.supplierCommitments}`) : 'N/A'}</td><td>{item.resourceAssignments ? (item.actualMinutes ? `${(item.actualMinutes / 60).toFixed(1)} h` : <span className="text-neutral-400">Missing</span>) : 'N/A'}</td><td>{item.finalPhotoCount || (item.stage === 'Job Done' ? <span className="text-amber-700">Legacy missing</span> : 'Not due')}</td><td>{item.costsConfirmed ? <span className="text-emerald-700">Confirmed</span> : item.stage === 'Job Done' ? <span className="text-amber-700">Missing</span> : 'Open'}</td><td>{item.learningCount}</td></tr>)}</tbody></table>{!data.jobs.length && <EmptyState title="No operational Jobs" description="Reports will populate from live Ongoing Job usage." />}</div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="p-4"><h3 className="text-sm font-semibold">Supplier delivery evidence</h3><p className="mt-1 text-2xs text-neutral-500">On-time rate is shown only where delivered and expected dates exist.</p></div><table className="crm-table w-full text-xs"><thead><tr className="crm-table-head"><th>Supplier</th><th>Commitments</th><th>Delivered</th><th>On time</th><th>Issues</th><th>Actual spend</th></tr></thead><tbody>{data.supplierPerformance.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.commitments}</td><td>{item.delivered}</td><td>{item.delivered ? `${Math.round((item.onTime / item.delivered) * 100)}%` : 'Not earned'}</td><td><Badge tone={item.issues ? 'warning' : 'neutral'}>{item.issues}</Badge></td><td>{money(item.actualSpend)}</td></tr>)}</tbody></table>{!data.supplierPerformance.length && <EmptyState title="No supplier evidence" description="Supplier performance will emerge from commitments and delivery records." />}</section><section className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="p-4"><h3 className="text-sm font-semibold">Service usage</h3><p className="mt-1 text-2xs text-neutral-500">Derived from Job work-package classifications, including visible unclassified work.</p></div><table className="crm-table w-full text-xs"><thead><tr className="crm-table-head"><th>Service</th><th>Jobs</th><th>Work packages</th></tr></thead><tbody>{data.servicePerformance.map((item) => <tr key={item.service}><td><strong>{item.service}</strong></td><td>{item.jobs}</td><td>{item.workPackages}</td></tr>)}</tbody></table>{!data.servicePerformance.length && <EmptyState title="No classified work packages" description="Service reporting will appear as Jobs use work packages and the service catalogue." />}</section></div>
  </PageSection></PageShell>;
}
