import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, CalendarDays, CheckSquare2, ChevronLeft, ChevronRight, GanttChart, List, MapPin, Plus, UserRound, UsersRound } from 'lucide-react';
import { crmApiFetch } from '../crmApi.js';
import { Alert, Badge, LoadingState, PageHeader, PageSection, PageShell, cn } from '../components/ui/primitives.jsx';
import { Modal } from '../components/ui/Modal.jsx';
import ActivityResourcePlanningModal from '../components/resources/ActivityResourcePlanningModal.jsx';

const STATUS_TONES = { completed: 'success', blocked: 'warning', in_progress: 'info', ready: 'success' };
const TYPE_LABELS = { site_survey: 'Site survey', design: 'Design', client_approval: 'Client approval', procurement: 'Procurement', printing: 'Printing', fabrication: 'Fabrication', packing: 'Packing', transport: 'Transport', installation: 'Installation', event_support: 'Event support', dismantling: 'Dismantling', return: 'Return', other: 'Other' };
function monthKey(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; }
function dateKey(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function startOfDay(date) { return new Date(date.getFullYear(), date.getMonth(), date.getDate()); }
function dateTimeValue(date) { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 16); }
function formatWhen(value) { return value ? new Date(value).toLocaleString('en-AE', { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' }) : 'Unscheduled'; }

function ActivityCard({ item, onOpen, onDragStart, compact = false }) {
  return <button draggable onDragStart={(event) => onDragStart(event, item)} onMouseDown={(event) => event.stopPropagation()} onClick={() => onOpen(item)} className={cn('block w-full rounded-md border border-neutral-200 bg-white text-left shadow-2xs hover:border-brand/40', compact ? 'p-1.5' : 'p-2.5')}>
    <div className="flex items-start justify-between gap-1"><span className="truncate text-[10px] font-semibold text-neutral-800">{item.title}</span><Badge tone={STATUS_TONES[item.status] || 'neutral'} className="px-1! py-0! text-[8px]!">{item.status.replace('_', ' ')}</Badge></div>
    <p className="mt-1 truncate text-[9px] text-neutral-500">{item.jobTitle}</p>
    {!compact && item.ownerName && <p className="mt-1 truncate text-[9px] text-neutral-400"><UserRound className="mr-1 inline h-2.5 w-2.5" />{item.ownerName}</p>}
    {!compact && item.locationName && <p className="truncate text-[9px] text-neutral-400"><MapPin className="mr-1 inline h-2.5 w-2.5" />{item.locationName}</p>}
    {!compact && item.resourceNames?.length > 0 && <p className="truncate text-[9px] text-neutral-400">{item.resourceNames.join(', ')}</p>}
    {!compact && (item.plannedLaborMinutes > 0 || item.actualMinutes > 0) && <p className="truncate text-[9px] text-neutral-400">{(Number(item.plannedLaborMinutes || 0) / 60).toFixed(1)}h planned · {(Number(item.actualMinutes || 0) / 60).toFixed(1)}h actual</p>}
    {item.hasResourceConflict && <p className="mt-1 flex items-center gap-1 text-[9px] font-semibold text-amber-700"><AlertTriangle className="h-2.5 w-2.5" />Resource conflict</p>}
  </button>;
}

function TaskDueCard({ item, onOpen, onDragStart, compact = false }) {
  const tone = item.status === 'blocked' ? 'border-red-200 bg-red-50 text-red-800' : item.status === 'waiting' ? 'border-violet-200 bg-violet-50 text-violet-800' : 'border-sky-200 bg-sky-50 text-sky-800';
  return <button draggable onDragStart={(event) => onDragStart(event, item)} onMouseDown={(event) => event.stopPropagation()} onClick={() => onOpen(item)} className={cn('block w-full rounded-md border text-left shadow-2xs hover:ring-1 hover:ring-brand/30', tone, compact ? 'p-1.5' : 'p-2.5')}>
    <div className="flex items-center gap-1"><CheckSquare2 className="h-3 w-3 shrink-0" /><span className="truncate text-[10px] font-semibold">{item.title}</span></div>
    {!compact && <p className="mt-1 truncate text-[9px] opacity-70">Task · {item.jobTitle || 'General'} · {item.ownerName || 'Unassigned'}</p>}
  </button>;
}

export default function PlanCalendarPage() {
  const navigate = useNavigate();
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [view, setView] = useState('calendar'); const [owner, setOwner] = useState(''); const [resource, setResource] = useState('');
  const [data, setData] = useState({ items: [], taskItems: [], users: [], jobs: [], resources: [], activityTypes: [] }); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [selection, setSelection] = useState(null); const [createOpen, setCreateOpen] = useState(false);
  const [selectedActivityId, setSelectedActivityId] = useState('');
  const [form, setForm] = useState({ jobId: '', title: '', activityType: 'other', ownerUserId: '', plannedStart: '', plannedEnd: '' });

  const load = useCallback(async () => {
    const from = new Date(month.getFullYear(), month.getMonth(), 1); const to = new Date(month.getFullYear(), month.getMonth() + 1, 0, 23, 59, 59);
    const params = new URLSearchParams({ from: from.toISOString(), to: to.toISOString() }); if (owner) params.set('ownerUserId', owner); if (resource) params.set('resourceId', resource);
    try { setError(''); setData(await crmApiFetch(`/api/admin/sales/plan-calendar?${params}`)); } catch (err) { setError(err.message || 'Failed to load plan calendar.'); } finally { setLoading(false); }
  }, [month, owner, resource]);
  useEffect(() => { setLoading(true); load(); }, [load]);

  const calendarCells = useMemo(() => {
    const first = new Date(month.getFullYear(), month.getMonth(), 1); const last = new Date(month.getFullYear(), month.getMonth() + 1, 0); const cells = [];
    for (let i = 0; i < first.getDay(); i += 1) cells.push(null); for (let day = 1; day <= last.getDate(); day += 1) cells.push(new Date(month.getFullYear(), month.getMonth(), day)); while (cells.length % 7) cells.push(null); return cells;
  }, [month]);
  const monthDays = useMemo(() => Array.from({ length: new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate() }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1)), [month]);
  const byDay = useMemo(() => {
    const grouped = {};
    for (const item of data.items || []) { const start = startOfDay(new Date(item.plannedStart)); const end = startOfDay(new Date(item.plannedEnd || item.plannedStart)); for (let cursor = new Date(start); cursor <= end; cursor.setDate(cursor.getDate() + 1)) (grouped[dateKey(cursor)] ||= []).push(item); }
    return grouped;
  }, [data.items]);
  const tasksByDay = useMemo(() => {
    const grouped = {}; for (const item of data.taskItems || []) { const day = new Date(item.dueAt); (grouped[dateKey(day)] ||= []).push(item); } return grouped;
  }, [data.taskItems]);
  const selectedRange = useMemo(() => {
    if (!selection) return null; const first = selection.anchor <= selection.current ? selection.anchor : selection.current; const last = selection.anchor <= selection.current ? selection.current : selection.anchor; return { first, last };
  }, [selection]);
  const selectedActivity = data.items.find((item) => item.id === selectedActivityId) || null;
  const resourceLanes = useMemo(() => {
    const lanes = (data.resources || []).map((item) => ({ ...item, items: data.items.filter((activity) => activity.resourceIds?.includes(item.id)) })).filter((item) => item.items.length || resource === item.id);
    const unassigned = data.items.filter((item) => !item.resourceIds?.length); if (unassigned.length) lanes.push({ id: 'unassigned', name: 'Unassigned', resourceType: 'attention', items: unassigned }); return lanes;
  }, [data.items, data.resources, resource]);

  function beginRange(date) { setSelection({ anchor: startOfDay(date), current: startOfDay(date) }); }
  function extendRange(date) { setSelection((current) => current ? { ...current, current: startOfDay(date) } : current); }
  function finishRange(date) {
    if (!selection) return; const anchor = selection.anchor; const current = startOfDay(date); const first = anchor <= current ? anchor : current; const last = anchor <= current ? current : anchor;
    const start = new Date(first); start.setHours(9, 0, 0, 0); const end = new Date(last); end.setHours(17, 0, 0, 0);
    setForm({ jobId: '', title: '', activityType: 'other', ownerUserId: owner || '', plannedStart: dateTimeValue(start), plannedEnd: dateTimeValue(end) }); setSelection(null); setCreateOpen(true);
  }
  function isSelected(day) { return selectedRange && day >= selectedRange.first && day <= selectedRange.last; }

  async function createActivity(event) {
    event.preventDefault(); if (!form.jobId) return; setBusy(true); setError('');
    try { await crmApiFetch(`/api/admin/sales/ongoing-jobs/${encodeURIComponent(form.jobId)}/production/activities`, { method: 'POST', body: JSON.stringify(form) }); setCreateOpen(false); await load(); }
    catch (err) { setError(err.message || 'Could not schedule activity.'); } finally { setBusy(false); }
  }
  function dragStart(event, item) { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('application/x-egs-activity', JSON.stringify({ id: item.id, jobId: item.jobId, start: item.plannedStart, end: item.plannedEnd })); }
  function dragTaskStart(event, item) { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('application/x-egs-task', JSON.stringify({ id: item.id, dueAt: item.dueAt })); }
  async function dropActivity(event, targetDay) {
    event.preventDefault(); const taskRaw = event.dataTransfer.getData('application/x-egs-task');
    if (taskRaw) {
      try { const item = JSON.parse(taskRaw); const oldDue = new Date(item.dueAt); const nextDue = new Date(targetDay); nextDue.setHours(oldDue.getHours(), oldDue.getMinutes(), 0, 0); setBusy(true); await crmApiFetch(`/api/admin/sales/tasks/${encodeURIComponent(item.id)}`, { method: 'PATCH', body: JSON.stringify({ dueAt: nextDue.toISOString() }) }); await load(); }
      catch (err) { setError(err.message || 'Could not reschedule task.'); } finally { setBusy(false); } return;
    }
    const raw = event.dataTransfer.getData('application/x-egs-activity'); if (!raw) return;
    try {
      const item = JSON.parse(raw); const oldStart = new Date(item.start); const oldEnd = new Date(item.end || item.start); const duration = Math.max(oldEnd.getTime() - oldStart.getTime(), 60 * 60 * 1000);
      const nextStart = new Date(targetDay); nextStart.setHours(oldStart.getHours(), oldStart.getMinutes(), 0, 0); const nextEnd = new Date(nextStart.getTime() + duration);
      setBusy(true); await crmApiFetch(`/api/admin/sales/ongoing-jobs/${encodeURIComponent(item.jobId)}/production/activities/${encodeURIComponent(item.id)}`, { method: 'PATCH', body: JSON.stringify({ plannedStart: nextStart.toISOString(), plannedEnd: nextEnd.toISOString() }) }); await load();
    } catch (err) { setError(err.message || 'Could not reschedule activity.'); } finally { setBusy(false); }
  }
  function openJob(item) { navigate(`/admin/crm/ongoing-jobs?recordType=ongoing_job&recordId=${item.jobId}`); }
  function openActivity(item) { setSelectedActivityId(item.id); }
  function openTask(item) { navigate(`/admin/crm/tasks?recordType=task&recordId=${item.id}`); }

  if (loading) return <PageShell><LoadingState label="Loading production planner…" /></PageShell>;
  return <PageShell className="max-w-none"><PageHeader /><PageSection>{error && <Alert>{error}</Alert>}
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><button className="crm-btn-secondary" onClick={() => setMonth((value) => new Date(value.getFullYear(), value.getMonth() - 1, 1))}><ChevronLeft className="h-4 w-4" /></button><input type="month" className="crm-input w-44" value={monthKey(month)} onChange={(e) => { const [year, value] = e.target.value.split('-').map(Number); setMonth(new Date(year, value - 1, 1)); }} /><button className="crm-btn-secondary" onClick={() => setMonth((value) => new Date(value.getFullYear(), value.getMonth() + 1, 1))}><ChevronRight className="h-4 w-4" /></button></div><div className="flex flex-wrap gap-2"><div className="crm-view-toggle">{[['calendar', CalendarDays, 'Calendar'], ['gantt', GanttChart, 'Gantt'], ['resources', UsersRound, 'Resources'], ['list', List, 'List']].map(([value, Icon, label]) => <button key={value} className={view === value ? 'is-active' : ''} onClick={() => setView(value)}><Icon className="h-4 w-4" />{label}</button>)}</div><select className="crm-select w-48" value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">All owners</option>{data.users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><select className="crm-select w-52" value={resource} onChange={(e) => setResource(e.target.value)}><option value="">All resources</option>{data.resources.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.resourceType}</option>)}</select></div></div>

    {view === 'calendar' && <div className="select-none overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="grid grid-cols-7 border-b border-neutral-200 bg-neutral-50">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((label) => <div key={label} className="px-2 py-2 text-center text-[10px] font-semibold uppercase tracking-wide text-neutral-500">{label}</div>)}</div><div className="grid grid-cols-7">{calendarCells.map((day, index) => <div key={day ? dateKey(day) : `blank-${index}`} onMouseDown={() => day && beginRange(day)} onMouseEnter={() => day && extendRange(day)} onMouseUp={() => day && finishRange(day)} onDragOver={(event) => day && event.preventDefault()} onDrop={(event) => day && dropActivity(event, day)} className={cn('min-h-40 border-b border-r border-neutral-100 p-2 transition', day && 'cursor-crosshair hover:bg-brand-soft/25', day && isSelected(day) && 'bg-brand-soft/70 ring-1 ring-inset ring-brand/30')}>{day && <><p className="mb-2 text-[11px] font-semibold text-neutral-500">{day.getDate()}</p><div className="space-y-1.5">{(tasksByDay[dateKey(day)] || []).map((item) => <TaskDueCard key={`task-${item.id}`} item={item} onOpen={openTask} onDragStart={dragTaskStart} compact />)}{(byDay[dateKey(day)] || []).map((item) => <ActivityCard key={`${item.id}-${dateKey(day)}`} item={item} onOpen={openJob} onDragStart={dragStart} compact />)}</div></>}</div>)}</div></div>}

    {view === 'gantt' && <div className="overflow-x-auto rounded-xl border border-neutral-200 bg-white"><div className="min-w-[1500px]"><div className="grid border-b border-neutral-200 bg-neutral-50" style={{ gridTemplateColumns: `240px repeat(${monthDays.length}, minmax(38px, 1fr))` }}><div className="sticky left-0 z-10 bg-neutral-50 p-3 text-[10px] font-semibold uppercase text-neutral-500">Job activity</div>{monthDays.map((day) => <div key={dateKey(day)} className="border-l border-neutral-200 p-2 text-center text-[9px] text-neutral-500">{day.getDate()}<br />{day.toLocaleDateString('en-AE', { weekday: 'short' }).slice(0, 2)}</div>)}</div><div className="grid border-b border-neutral-200" style={{ gridTemplateColumns: `240px repeat(${monthDays.length}, minmax(38px, 1fr))` }}><div className="sticky left-0 z-10 flex items-center gap-2 bg-brand-soft p-3 text-[10px] font-semibold text-brand"><Plus className="h-3.5 w-3.5" />Drag across dates to add</div>{monthDays.map((day) => <div key={dateKey(day)} onMouseDown={() => beginRange(day)} onMouseEnter={() => extendRange(day)} onMouseUp={() => finishRange(day)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => dropActivity(event, day)} className={cn('h-12 cursor-crosshair border-l border-neutral-100 hover:bg-brand-soft/40', isSelected(day) && 'bg-brand-soft ring-1 ring-inset ring-brand/30')} />)}</div>{data.items.map((item) => { const monthStart = new Date(month.getFullYear(), month.getMonth(), 1); const monthEnd = new Date(month.getFullYear(), month.getMonth() + 1, 0); const start = new Date(Math.max(startOfDay(new Date(item.plannedStart)), monthStart)); const end = new Date(Math.min(startOfDay(new Date(item.plannedEnd || item.plannedStart)), monthEnd)); const first = start.getDate() + 1; const last = end.getDate() + 2; return <div key={item.id} className="grid min-h-14 border-b border-neutral-100" style={{ gridTemplateColumns: `240px repeat(${monthDays.length}, minmax(38px, 1fr))` }}><button onClick={() => openJob(item)} className="sticky left-0 z-10 bg-white p-3 text-left"><p className="truncate text-[10px] font-semibold text-neutral-800">{item.title}</p><p className="truncate text-[9px] text-neutral-500">{item.jobTitle} · {item.ownerName || 'Unassigned'}</p></button>{monthDays.map((day) => <div key={dateKey(day)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => dropActivity(event, day)} className="border-l border-neutral-100" />)}<button draggable onDragStart={(event) => dragStart(event, item)} onClick={() => openJob(item)} className="z-5 m-1 truncate rounded-md bg-brand px-2 text-left text-[9px] font-semibold text-white shadow-sm" style={{ gridColumn: `${first} / ${last}`, gridRow: 1 }}>{item.title} · {item.status.replace('_', ' ')}</button></div>; })}</div></div>}

    {view === 'list' && <div className="space-y-4"><div className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="border-b border-neutral-200 p-3"><h3 className="text-xs font-semibold">Scheduled activities</h3></div><table className="crm-table w-full text-xs"><thead><tr className="crm-table-head"><th>Activity</th><th>Job</th><th>Start</th><th>End</th><th>Resources</th><th>Location</th><th>Status</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id} draggable onDragStart={(event) => dragStart(event, item)} onClick={() => openJob(item)} className="cursor-pointer"><td><strong>{item.title}</strong><p className="text-[10px] text-neutral-400">{TYPE_LABELS[item.activityType]}</p></td><td>{item.jobTitle}</td><td>{formatWhen(item.plannedStart)}</td><td>{formatWhen(item.plannedEnd)}</td><td>{item.resourceNames?.join(', ') || item.ownerName || 'Unassigned'}{item.hasResourceConflict && <p className="text-[10px] font-semibold text-amber-700">Conflict</p>}</td><td>{item.locationName || '—'}</td><td><Badge tone={STATUS_TONES[item.status] || 'neutral'}>{item.status.replace('_', ' ')}</Badge></td></tr>)}</tbody></table>{!data.items.length && <p className="p-8 text-center text-xs text-neutral-400">No activities in this month.</p>}</div><div className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="border-b border-neutral-200 p-3"><h3 className="text-xs font-semibold">Tasks due</h3></div><table className="crm-table w-full text-xs"><thead><tr className="crm-table-head"><th>Task</th><th>Job / context</th><th>Due</th><th>Owner</th><th>Status</th></tr></thead><tbody>{(data.taskItems || []).map((item) => <tr key={item.id} draggable onDragStart={(event) => dragTaskStart(event, item)} onClick={() => openTask(item)} className="cursor-pointer"><td><strong>{item.title}</strong></td><td>{item.jobTitle || 'General'}{item.workPackageTitle && <p className="text-[10px] text-neutral-400">{item.workPackageTitle}</p>}</td><td>{formatWhen(item.dueAt)}</td><td>{item.ownerName || 'Unassigned'}</td><td><Badge tone={item.status === 'blocked' ? 'warning' : item.status === 'waiting' ? 'info' : 'neutral'}>{item.status}</Badge></td></tr>)}</tbody></table>{!data.taskItems?.length && <p className="p-8 text-center text-xs text-neutral-400">No tasks due in this month.</p>}</div></div>}

    {view === 'resources' && <div className="overflow-x-auto rounded-xl border border-neutral-200 bg-white"><div className="min-w-[1500px]"><div className="grid border-b border-neutral-200 bg-neutral-50" style={{ gridTemplateColumns: `240px repeat(${monthDays.length}, minmax(38px, 1fr))` }}><div className="sticky left-0 z-10 bg-neutral-50 p-3 text-[10px] font-semibold uppercase text-neutral-500">Resource lane</div>{monthDays.map((day) => <div key={dateKey(day)} className="border-l border-neutral-200 p-2 text-center text-[9px] text-neutral-500">{day.getDate()}<br />{day.toLocaleDateString('en-AE', { weekday: 'short' }).slice(0, 2)}</div>)}</div>{resourceLanes.map((lane) => <div key={lane.id} className="relative grid min-h-18 border-b border-neutral-100" style={{ gridTemplateColumns: `240px repeat(${monthDays.length}, minmax(38px, 1fr))` }}><div className="sticky left-0 z-10 bg-white p-3"><p className="truncate text-[10px] font-semibold text-neutral-800">{lane.name}</p><p className="text-[9px] capitalize text-neutral-400">{lane.resourceType.replaceAll('_', ' ')}{lane.hourlyCostAed != null ? ` · AED ${lane.hourlyCostAed}/h` : ''}</p></div>{monthDays.map((day) => <div key={dateKey(day)} className="border-l border-neutral-100" />)}{lane.items.map((item, index) => { const monthStart = new Date(month.getFullYear(), month.getMonth(), 1); const monthEnd = new Date(month.getFullYear(), month.getMonth() + 1, 0); const start = new Date(Math.max(startOfDay(new Date(item.plannedStart)), monthStart)); const end = new Date(Math.min(startOfDay(new Date(item.plannedEnd || item.plannedStart)), monthEnd)); const first = start.getDate() + 1; const last = end.getDate() + 2; const assignment = item.resourceAssignments?.find((value) => value.resourceId === lane.id); return <button key={`${lane.id}-${item.id}`} onClick={() => openActivity(item)} className={`z-5 m-1 truncate rounded-md px-2 text-left text-[9px] font-semibold text-white shadow-sm ${item.hasResourceConflict ? 'bg-amber-600' : 'bg-brand'}`} style={{ gridColumn: `${first} / ${last}`, gridRow: index + 1, minHeight: 28 }} title={`${item.jobTitle} · ${item.title}`}>{item.title}{assignment?.plannedMinutes != null ? ` · ${(Number(assignment.plannedMinutes) / 60).toFixed(1)}h` : ''}</button>; })}</div>)}{!resourceLanes.length && <p className="p-10 text-center text-xs text-neutral-400">No assigned or unassigned activities in this month.</p>}</div></div>}

    <p className="mt-3 text-[10px] text-neutral-400">Activities reserve time and resources; tasks are accountable actions due on a date. Both are shown here from their original records. Drag either one to reschedule it.</p>
    <ActivityResourcePlanningModal item={selectedActivity} resources={data.resources} onClose={() => setSelectedActivityId('')} onChanged={load} onOpenJob={openJob} />
    <Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Schedule Job activity" subtitle="The selected date range is already filled. Choose the Job before saving." icon={CalendarDays} size="md" footer={<><button className="crm-btn-secondary" onClick={() => setCreateOpen(false)}>Cancel</button><button type="submit" form="calendar-activity-form" className="crm-btn-primary" disabled={busy || !form.jobId || !form.title.trim()}>{busy ? 'Scheduling…' : 'Schedule activity'}</button></>}><form id="calendar-activity-form" onSubmit={createActivity} className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium text-neutral-600 sm:col-span-2">Ongoing Job<select className="crm-select mt-1.5 w-full" value={form.jobId} onChange={(e) => setForm((v) => ({ ...v, jobId: e.target.value }))} required><option value="">Select the Job…</option>{data.jobs.map((job) => <option key={job.id} value={job.id}>{job.jobNumber ? `${job.jobNumber} · ` : ''}{job.name}</option>)}</select></label><label className="text-xs font-medium text-neutral-600 sm:col-span-2">Activity<input className="crm-input mt-1.5 w-full" value={form.title} onChange={(e) => setForm((v) => ({ ...v, title: e.target.value }))} placeholder="e.g. Install reception signage" required /></label><label className="text-xs font-medium text-neutral-600">Type<select className="crm-select mt-1.5 w-full" value={form.activityType} onChange={(e) => setForm((v) => ({ ...v, activityType: e.target.value }))}>{data.activityTypes.map((type) => <option key={type} value={type}>{TYPE_LABELS[type]}</option>)}</select></label><label className="text-xs font-medium text-neutral-600">Owner<select className="crm-select mt-1.5 w-full" value={form.ownerUserId} onChange={(e) => setForm((v) => ({ ...v, ownerUserId: e.target.value }))}><option value="">Assign later</option>{data.users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label className="text-xs font-medium text-neutral-600">Starts<input type="datetime-local" className="crm-input mt-1.5 w-full" value={form.plannedStart} onChange={(e) => setForm((v) => ({ ...v, plannedStart: e.target.value }))} /></label><label className="text-xs font-medium text-neutral-600">Ends<input type="datetime-local" className="crm-input mt-1.5 w-full" value={form.plannedEnd} onChange={(e) => setForm((v) => ({ ...v, plannedEnd: e.target.value }))} /></label></form></Modal>
  </PageSection></PageShell>;
}
