import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, BriefcaseBusiness, CalendarClock, Camera, CheckCircle2, ChevronRight, Clock3, FileCheck2, MapPin, PackageCheck, Pause, Play, RefreshCw, Send, Truck, Users } from 'lucide-react';
import { crmApiFetch } from '../crmApi.js';
import { Alert, Badge, EmptyState, LoadingState, PageShell, cn } from '../components/ui/primitives.jsx';
import { Modal } from '../components/ui/Modal.jsx';

function dateValue() { const value = new Date(); value.setMinutes(value.getMinutes() - value.getTimezoneOffset()); return value.toISOString().slice(0, 10); }
function when(value) { return value ? new Date(value).toLocaleString('en-AE', { weekday: 'short', day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' }) : 'Time not scheduled'; }
const STATUS_TONE = { not_started: 'neutral', ready: 'info', in_progress: 'info', blocked: 'warning', completed: 'success' };
const GROUPS = [
  ['overdue', 'Needs attention', AlertTriangle, 'text-red-700'],
  ['today', 'Today', Clock3, 'text-brand'],
  ['upcoming', 'Next 7 days', CalendarClock, 'text-sky-700'],
  ['completed', 'Completed today', CheckCircle2, 'text-emerald-700'],
];

function ActivityCard({ item, onOpen }) {
  return <button type="button" onClick={() => onOpen(item)} className="w-full rounded-2xl border border-neutral-200 bg-white p-4 text-left shadow-sm transition hover:border-brand/30 hover:shadow-md active:scale-[0.995]">
    <div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge tone={STATUS_TONE[item.status] || 'neutral'}>{item.status.replaceAll('_', ' ')}</Badge>{item.runningTimerId && <span className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2 py-1 text-2xs font-semibold text-emerald-700"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-500" />Timer running</span>}</div><h3 className="mt-2 text-base font-bold text-neutral-900">{item.title}</h3><p className="mt-1 text-xs font-medium text-neutral-600">{item.jobNumber ? `${item.jobNumber} · ` : ''}{item.jobTitle}</p></div><ChevronRight className="mt-1 h-5 w-5 shrink-0 text-neutral-300" /></div>
    <div className="mt-3 grid gap-2 text-xs text-neutral-500 sm:grid-cols-2"><span><Clock3 className="mr-1.5 inline h-3.5 w-3.5" />{when(item.plannedStart)}</span><span><MapPin className="mr-1.5 inline h-3.5 w-3.5" />{item.locationName || item.city || 'Location not recorded'}</span>{item.workPackageTitle && <span><BriefcaseBusiness className="mr-1.5 inline h-3.5 w-3.5" />{item.workPackageTitle}</span>}<span><Users className="mr-1.5 inline h-3.5 w-3.5" />{item.resources?.map((resource) => resource.name).join(', ') || item.ownerName || 'Assigned to you'}</span></div>
    {item.blocker && <p className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-xs font-medium text-red-700">Blocked: {item.blocker}</p>}
  </button>;
}

function MiniList({ icon: Icon, title, items, render, empty }) {
  return <section className="rounded-xl border border-neutral-200 bg-white p-3"><h4 className="flex items-center gap-2 text-xs font-semibold text-neutral-800"><Icon className="h-4 w-4 text-brand" />{title}</h4><div className="mt-2 space-y-2">{items?.map(render)}{!items?.length && <p className="text-xs text-neutral-400">{empty}</p>}</div></section>;
}

function FieldActionModal({ item, onClose, onChanged }) {
  const [note, setNote] = useState(''); const [remainingWork, setRemainingWork] = useState(''); const [photoType, setPhotoType] = useState(item.activityType === 'installation' ? 'installation_photo' : 'progress_photo'); const [photos, setPhotos] = useState([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(action) {
    setBusy(true); setError('');
    try {
      const body = new FormData(); body.append('action', action); body.append('note', note); body.append('remainingWork', remainingWork); body.append('photoType', action === 'problem' && photoType === 'progress_photo' ? 'problem_photo' : photoType); photos.forEach((photo) => body.append('photos', photo));
      await crmApiFetch(`/api/admin/field/activities/${encodeURIComponent(item.id)}/actions`, { method: 'POST', body }); await onChanged(); onClose();
    } catch (err) { setError(err.message || 'Could not save field update.'); } finally { setBusy(false); }
  }
  const evidence = item.updates?.filter((update) => update.url) || [];
  return <Modal open onClose={onClose} title={item.title} subtitle={`${item.jobNumber ? `${item.jobNumber} · ` : ''}${item.jobTitle}`} size="xl">
    {error && <Alert>{error}</Alert>}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(280px,0.9fr)]">
      <div className="space-y-4">
        <section className="rounded-2xl bg-neutral-950 p-4 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge tone={item.status === 'blocked' ? 'warning' : 'info'}>{item.status.replaceAll('_', ' ')}</Badge><p className="mt-2 text-sm font-semibold">{when(item.plannedStart)} – {when(item.plannedEnd)}</p><p className="mt-1 text-xs text-white/55"><MapPin className="mr-1 inline h-3.5 w-3.5" />{[item.locationName, item.address, item.city].filter(Boolean).join(' · ') || 'Location not recorded'}</p></div>{item.runningTimerId ? <button className="rounded-xl bg-amber-400 px-4 py-3 text-xs font-bold text-neutral-950" disabled={busy} onClick={() => submit('pause')}><Pause className="mr-1 inline h-4 w-4" />Pause timer</button> : <button className="rounded-xl bg-emerald-400 px-4 py-3 text-xs font-bold text-neutral-950" disabled={busy || item.status === 'completed'} onClick={() => submit('start')}><Play className="mr-1 inline h-4 w-4" />Start work</button>}</div></section>
        <label className="block"><span className="text-xs font-semibold text-neutral-700">What happened?</span><textarea rows={4} className="crm-input mt-1.5 resize-y" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Short update, completion note, or exact problem…" /></label>
        <label className="block"><span className="text-xs font-semibold text-neutral-700">What remains?</span><textarea rows={2} className="crm-input mt-1.5 resize-y" value={remainingWork} onChange={(event) => setRemainingWork(event.target.value)} placeholder="Leave blank when this activity is fully complete." /></label>
        <div className="rounded-2xl border-2 border-dashed border-neutral-200 bg-neutral-50 p-4"><div className="flex items-center gap-2"><Camera className="h-5 w-5 text-brand" /><div><p className="text-xs font-semibold">Take or attach photographs</p><p className="text-2xs text-neutral-500">Photos are added to this activity and Job Memory.</p></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className="crm-select text-xs" value={photoType} onChange={(event) => setPhotoType(event.target.value)}><option value="progress_photo">Progress photo</option><option value="installation_photo">Installation photo</option><option value="final_photo">Final delivery photo</option><option value="problem_photo">Problem / snag photo</option></select><input type="file" accept="image/*" capture="environment" multiple className="block w-full text-xs text-neutral-500" onChange={(event) => setPhotos([...event.target.files])} /></div>{photos.length > 0 && <p className="mt-2 text-2xs font-semibold text-emerald-700">{photos.length} photo{photos.length === 1 ? '' : 's'} ready</p>}</div>
        <div className="grid grid-cols-1 gap-2 sm:grid-cols-3"><button className="crm-btn-secondary min-h-12 justify-center" disabled={busy || (!note.trim() && !remainingWork.trim() && !photos.length)} onClick={() => submit('progress')}><Send className="h-4 w-4" />Save progress</button><button className="min-h-12 rounded-xl border border-red-200 bg-red-50 px-4 text-xs font-bold text-red-700" disabled={busy || !note.trim()} onClick={() => submit('problem')}><AlertTriangle className="mr-1 inline h-4 w-4" />Report problem</button><button className="min-h-12 rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white disabled:opacity-50" disabled={busy || Boolean(remainingWork.trim()) || item.status === 'completed'} onClick={() => submit('complete')}><CheckCircle2 className="mr-1 inline h-4 w-4" />Complete</button></div>
        {remainingWork.trim() && <p className="text-2xs text-amber-700">Save this as progress. Completion becomes available when no work remains.</p>}
      </div>
      <aside className="space-y-3">
        <MiniList icon={FileCheck2} title="Approved production documents" items={item.documents} empty="No active production release documents." render={(doc) => <a key={`${doc.type}-${doc.url}`} href={doc.url} target="_blank" rel="noreferrer" className="block rounded-lg bg-emerald-50 p-2 text-xs text-emerald-800 hover:underline"><strong>{doc.type === 'design' ? 'Design' : 'Quotation'} v{doc.version}</strong><br />{doc.title || doc.fileName}</a>} />
        <MiniList icon={PackageCheck} title="Materials and stock" items={item.inventory} empty="No active stock reservations for this work." render={(entry) => <div key={entry.id} className="rounded-lg bg-neutral-50 p-2 text-xs"><strong>{entry.itemName}</strong><p className="text-neutral-500">{entry.quantity} · {entry.assetTag || entry.sku}</p></div>} />
        <MiniList icon={Truck} title="Supplier deliveries" items={item.suppliers} empty="No supplier commitments linked to this work." render={(entry) => <div key={entry.id} className="rounded-lg bg-neutral-50 p-2 text-xs"><strong>{entry.supplierName}</strong><p className="text-neutral-500">{entry.description} · {entry.status.replaceAll('_', ' ')}</p>{entry.expectedDeliveryAt && <p className="text-neutral-400">Expected {when(entry.expectedDeliveryAt)}</p>}</div>} />
        <MiniList icon={Users} title="Crew, vehicles and equipment" items={item.resources} empty="No resources assigned." render={(entry) => <div key={entry.id} className="flex items-center justify-between rounded-lg bg-neutral-50 p-2 text-xs"><strong>{entry.name}</strong><span className="capitalize text-neutral-400">{entry.type}</span></div>} />
        <MiniList icon={Camera} title={`Existing evidence · ${item.evidenceCount}`} items={evidence.slice(0, 6)} empty="No activity photos yet." render={(entry) => <a key={entry.id} href={entry.url} target="_blank" rel="noreferrer" className="block truncate text-xs text-brand hover:underline">{entry.fileName || 'Open evidence'}</a>} />
      </aside>
    </div>
  </Modal>;
}

export default function TodayPage() {
  const navigate = useNavigate(); const [date, setDate] = useState(dateValue); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState(null);
  const load = useCallback(async () => { try { setError(''); setData(await crmApiFetch(`/api/admin/field/today?date=${encodeURIComponent(date)}`)); } catch (err) { setError(err.message || 'Could not load Today workspace.'); } finally { setLoading(false); } }, [date]);
  useEffect(() => { setLoading(true); load(); }, [load]);
  const hasWork = useMemo(() => data && Object.values(data.groups).some((items) => items.length), [data]);
  if (loading) return <PageShell><LoadingState label="Loading today’s field work…" /></PageShell>;
  return <PageShell className="max-w-6xl pb-24"><div className="sticky top-0 z-10 -mx-4 mb-4 border-b border-neutral-200 bg-[var(--color-canvas)]/95 px-4 py-3 backdrop-blur sm:-mx-6 sm:px-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-2xs font-bold uppercase tracking-[0.2em] text-brand">Field execution</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-neutral-900">Today</h1><p className="text-xs text-neutral-500">{data?.resource ? `${data.resource.name} · ${data.resource.resourceType}` : 'Your assigned operational work'}</p></div><div className="flex gap-2"><input type="date" className="crm-input w-40" value={date} onChange={(event) => setDate(event.target.value)} /><button className="crm-btn-secondary px-3!" onClick={load} title="Refresh" aria-label="Refresh"><RefreshCw className="h-4 w-4" /></button></div></div></div>
    {error && <Alert>{error}</Alert>}
    {data?.resourceRequired && <Alert tone="warning">Your login is not linked to an Employee or Contractor resource yet. Activities owned directly by your user still appear, but project-time recording requires the employee link.</Alert>}
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{[['Today',data.summary.today,Clock3],['Attention',data.summary.overdue,AlertTriangle],['Upcoming',data.summary.upcoming,CalendarClock],['Completed',data.summary.completed,CheckCircle2],['My tasks',data.summary.openTasks,FileCheck2],['Timers',data.summary.runningTimers,Play]].map(([label,value,Icon]) => <div key={label} className="rounded-xl border border-neutral-200 bg-white p-3"><div className="flex items-center justify-between text-neutral-400"><span className="text-2xs font-bold uppercase tracking-wide">{label}</span><Icon className="h-3.5 w-3.5" /></div><p className="mt-2 text-2xl font-bold text-neutral-900">{value}</p></div>)}</div>
    <div className="mt-5 space-y-6">{GROUPS.map(([key,label,Icon,color]) => data.groups[key].length ? <section key={key}><div className={`mb-2 flex items-center gap-2 ${color}`}><Icon className="h-4 w-4" /><h2 className="text-xs font-bold uppercase tracking-wide">{label}</h2><span className="text-2xs">{data.groups[key].length}</span></div><div className="grid gap-3 lg:grid-cols-2">{data.groups[key].map((item) => <ActivityCard key={item.id} item={item} onOpen={setSelected} />)}</div></section> : null)}</div>
    {!hasWork && <div className="mt-6"><EmptyState icon={CheckCircle2} title="No assigned field activities" description="Nothing scheduled or overdue for this date. Activities appear when your ERP user owns them or your employee resource is assigned." /></div>}
    <section className="mt-7 rounded-2xl border border-neutral-200 bg-white p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">My open tasks</h2><p className="text-xs text-neutral-500">Accountable actions remain in the unified task system.</p></div><button className="crm-btn-ghost text-xs" onClick={() => navigate('/admin/crm/tasks')}>All tasks <ChevronRight className="h-3.5 w-3.5" /></button></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{data.tasks.slice(0, 8).map((task) => <button key={task.id} className={cn('rounded-xl border p-3 text-left', task.status === 'blocked' ? 'border-red-200 bg-red-50' : task.status === 'waiting' ? 'border-violet-200 bg-violet-50' : 'border-neutral-200 bg-neutral-50')} onClick={() => navigate(`/admin/crm/tasks?recordType=task&recordId=${task.id}`)}><div className="flex items-center justify-between gap-2"><strong className="text-xs">{task.title}</strong><Badge tone={task.status === 'blocked' ? 'warning' : 'neutral'}>{task.status}</Badge></div><p className="mt-1 text-2xs text-neutral-500">{task.jobTitle || 'General'} · {task.dueAt ? when(task.dueAt) : 'No due date'}</p></button>)}{!data.tasks.length && <p className="text-xs text-neutral-400">No open tasks assigned to you.</p>}</div></section>
    {selected && <FieldActionModal item={selected} onClose={() => setSelected(null)} onChanged={load} />}
  </PageShell>;
}
