import db from '../db/index.js';
import { writeAuditLog } from './auditService.js';

export const ESTIMATE_CATEGORIES = Object.freeze(['material', 'labor', 'supplier', 'transport', 'permit', 'rental', 'other']);
export const OTHER_ACTUAL_CATEGORIES = Object.freeze(['transport', 'permit', 'rental', 'petty_cash', 'other']);

function text(value) { return String(value ?? '').trim() || null; }
function uuid(value) { const result = text(value); return result && /^[0-9a-f-]{36}$/i.test(result) ? result : null; }
function money(value, label = 'Amount') { const result = Number(value); if (!Number.isFinite(result) || result < 0) throw Object.assign(new Error(`${label} must be zero or more.`), { status: 400 }); return result; }
function timestamp(value) { if (!value) return new Date(); const result = new Date(value); if (Number.isNaN(result.getTime())) throw Object.assign(new Error('A valid date and time is required.'), { status: 400 }); return result; }
function numeric(row, fields) { const result = { ...row }; fields.forEach((field) => { result[field] = Number(result[field] || 0); }); return result; }
async function audit(actor, action, resource, resourceId, summary, jobId) { await writeAuditLog({ userId: actor?.userId, userDisplayName: actor?.displayName || 'EGS Team', action, resource, resourceId, summary, metadata: { ongoingJobId: jobId } }); }

async function requireJob(jobId, client = db) {
  const id = uuid(jobId); if (!id) throw Object.assign(new Error('Valid Job is required.'), { status: 400 });
  const result = await client.query(`SELECT id, title, summary_stage AS stage FROM ongoing_jobs WHERE id=$1::uuid AND deleted_at IS NULL`, [id]);
  if (!result.rows.length) throw Object.assign(new Error('Ongoing Job not found.'), { status: 404 }); return result.rows[0];
}

async function validateWorkPackage(jobId, workPackageId, client = db) {
  const id = uuid(workPackageId); if (!id) return null;
  const result = await client.query(`SELECT id FROM job_scope_lines WHERE id=$1::uuid AND ongoing_job_id=$2::uuid AND archived_at IS NULL`, [id, jobId]);
  if (!result.rows.length) throw Object.assign(new Error('Work package does not belong to this Job.'), { status: 400 }); return id;
}

export async function getJobCosting(jobId) {
  const job = await requireJob(jobId);
  const [workPackages, estimates, otherActuals, supplier, labor, material, quote, confirmation, missingSupplier, missingLabor, missingMaterial] = await Promise.all([
    db.query(`SELECT id, COALESCE(title, description, 'Untitled work package') AS title FROM job_scope_lines WHERE ongoing_job_id=$1::uuid AND archived_at IS NULL ORDER BY display_order, created_at`, [job.id]),
    db.query(`SELECT e.id, e.work_package_id AS "workPackageId", COALESCE(w.title,w.description) AS "workPackageTitle", e.category, e.description, e.estimated_amount_aed AS amount, e.created_at AS "createdAt", COALESCE(u.name,'EGS Team') AS author FROM job_cost_estimates e LEFT JOIN job_scope_lines w ON w.id=e.work_package_id LEFT JOIN users u ON u.id=e.created_by_user_id WHERE e.ongoing_job_id=$1::uuid AND e.archived_at IS NULL ORDER BY e.category,e.created_at`, [job.id]),
    db.query(`SELECT c.id, c.work_package_id AS "workPackageId", COALESCE(w.title,w.description) AS "workPackageTitle", c.category, c.description, c.amount_aed AS amount, c.reference, c.occurred_at AS "occurredAt", COALESCE(u.name,'EGS Team') AS author FROM job_actual_costs c LEFT JOIN job_scope_lines w ON w.id=c.work_package_id LEFT JOIN users u ON u.id=c.created_by_user_id WHERE c.ongoing_job_id=$1::uuid AND c.voided_at IS NULL ORDER BY c.occurred_at DESC`, [job.id]),
    db.query(`SELECT sc.id, sc.work_package_id AS "workPackageId", COALESCE(w.title,w.description) AS "workPackageTitle", o.canonical_name AS "supplierName", sc.description, sc.committed_amount AS committed, sc.actual_amount AS actual, sc.status FROM supplier_commitments sc JOIN supplier_profiles sp ON sp.id=sc.supplier_profile_id JOIN organizations o ON o.id=sp.organization_id LEFT JOIN job_scope_lines w ON w.id=sc.work_package_id WHERE sc.ongoing_job_id=$1::uuid AND sc.status<>'cancelled' ORDER BY sc.created_at`, [job.id]),
    db.query(`SELECT te.work_package_id AS "workPackageId", COALESCE(w.title,w.description) AS "workPackageTitle", SUM(te.duration_minutes)::int AS minutes, SUM((te.duration_minutes/60.0)*r.hourly_cost_aed) AS actual FROM project_time_entries te JOIN operational_resources r ON r.id=te.resource_id LEFT JOIN job_scope_lines w ON w.id=te.work_package_id WHERE te.ongoing_job_id=$1::uuid AND te.status='completed' AND r.hourly_cost_aed IS NOT NULL GROUP BY te.work_package_id,w.title,w.description ORDER BY "workPackageTitle" NULLS FIRST`, [job.id]),
    db.query(`SELECT m.id, m.work_package_id AS "workPackageId", COALESCE(w.title,w.description) AS "workPackageTitle", i.name AS "itemName", m.movement_type AS "movementType", m.quantity, m.unit_cost_aed AS "unitCost", (m.quantity*m.unit_cost_aed) AS actual, m.occurred_at AS "occurredAt" FROM inventory_movements m JOIN inventory_items i ON i.id=m.inventory_item_id LEFT JOIN job_scope_lines w ON w.id=m.work_package_id WHERE m.ongoing_job_id=$1::uuid AND m.movement_type IN ('consumption','damage','loss') ORDER BY m.occurred_at DESC`, [job.id]),
    db.query(`SELECT qv.id AS "versionId", qv.total_amount AS amount, q.quote_family_number AS "familyNumber", q.title FROM artifact_decisions ad JOIN quote_versions qv ON qv.id=ad.quote_version_id JOIN quotes q ON q.id=qv.quote_id WHERE ad.ongoing_job_id=$1::uuid AND ad.artifact_type='quotation' AND ad.decision='approved' ORDER BY ad.decided_at DESC LIMIT 1`, [job.id]),
    db.query(`SELECT c.confirmed_at AS "confirmedAt", c.confirmation_note AS note, c.reopened_at AS "reopenedAt", COALESCE(u.name,'EGS Team') AS "confirmedBy" FROM job_cost_confirmations c LEFT JOIN users u ON u.id=c.confirmed_by_user_id WHERE c.ongoing_job_id=$1::uuid`, [job.id]),
    db.query(`SELECT COUNT(*)::int AS count FROM supplier_commitments WHERE ongoing_job_id=$1::uuid AND status<>'cancelled' AND actual_amount IS NULL`, [job.id]),
    db.query(`SELECT COUNT(*)::int AS count FROM project_time_entries te JOIN operational_resources r ON r.id=te.resource_id WHERE te.ongoing_job_id=$1::uuid AND te.status='completed' AND r.hourly_cost_aed IS NULL`, [job.id]),
    db.query(`SELECT COUNT(*)::int AS count FROM inventory_movements WHERE ongoing_job_id=$1::uuid AND movement_type IN ('consumption','damage','loss') AND unit_cost_aed IS NULL`, [job.id]),
  ]);

  const estimateRows = estimates.rows.map((row) => numeric(row, ['amount']));
  const otherRows = otherActuals.rows.map((row) => numeric(row, ['amount']));
  const supplierRows = supplier.rows.map((row) => ({ ...numeric(row, ['committed']), actual: row.actual == null ? null : Number(row.actual) }));
  const laborRows = labor.rows.map((row) => numeric(row, ['minutes', 'actual']));
  const materialRows = material.rows.map((row) => ({ ...numeric(row, ['quantity']), unitCost: row.unitCost == null ? null : Number(row.unitCost), actual: row.actual == null ? null : Number(row.actual) }));
  const approvedQuote = quote.rows[0] ? numeric(quote.rows[0], ['amount']) : null;
  const quoteRevenue = approvedQuote ? await db.query(`SELECT work_package_id AS "workPackageId",SUM(line_total) AS revenue FROM quote_lines WHERE quote_version_id=$1::uuid GROUP BY work_package_id`,[approvedQuote.versionId]) : {rows:[]};
  const costConfirmation = confirmation.rows[0] ? { ...confirmation.rows[0], active: !confirmation.rows[0].reopenedAt } : null;
  const actualSupplier = supplierRows.reduce((sum, row) => sum + (row.actual || 0), 0);
  const committedSupplier = supplierRows.reduce((sum, row) => sum + row.committed, 0);
  const actualLabor = laborRows.reduce((sum, row) => sum + row.actual, 0);
  const actualMaterial = materialRows.reduce((sum, row) => sum + (row.actual || 0), 0);
  const actualOther = otherRows.reduce((sum, row) => sum + row.amount, 0);
  const actualTotal = actualSupplier + actualLabor + actualMaterial + actualOther;
  const estimatedTotal = estimateRows.reduce((sum, row) => sum + row.amount, 0);
  const revenue = approvedQuote?.amount || 0;
  const issues = { supplierActualsMissing: missingSupplier.rows[0].count, laborRatesMissing: missingLabor.rows[0].count, materialPricesMissing: missingMaterial.rows[0].count, approvedQuotationMissing: !approvedQuote };
  const marginReady = Boolean(costConfirmation?.active && approvedQuote && !issues.supplierActualsMissing && !issues.laborRatesMissing && !issues.materialPricesMissing);
  const reconciliationMap=new Map([[null,{workPackageId:null,workPackageTitle:'Whole Job',quotedRevenue:0,estimated:0,committed:0,actual:0}]]); workPackages.rows.forEach((pack)=>reconciliationMap.set(pack.id,{workPackageId:pack.id,workPackageTitle:pack.title,quotedRevenue:0,estimated:0,committed:0,actual:0})); const rowFor=(id)=>reconciliationMap.get(id||null)||reconciliationMap.get(null);
  estimateRows.forEach((row)=>{rowFor(row.workPackageId).estimated+=row.amount;}); supplierRows.forEach((row)=>{rowFor(row.workPackageId).committed+=row.committed; rowFor(row.workPackageId).actual+=row.actual||0;}); laborRows.forEach((row)=>{rowFor(row.workPackageId).actual+=row.actual;}); materialRows.forEach((row)=>{rowFor(row.workPackageId).actual+=row.actual||0;}); otherRows.forEach((row)=>{rowFor(row.workPackageId).actual+=row.amount;}); quoteRevenue.rows.forEach((row)=>{rowFor(row.workPackageId).quotedRevenue+=Number(row.revenue||0);}); if(approvedQuote&&!quoteRevenue.rows.length) rowFor(null).quotedRevenue=approvedQuote.amount;
  const reconciliation=[...reconciliationMap.values()].map((row)=>({...row,estimatedVariance:row.estimated-row.actual,actualMargin:marginReady&&row.quotedRevenue>0?row.quotedRevenue-row.actual:null})).filter((row)=>row.workPackageId||row.quotedRevenue||row.estimated||row.committed||row.actual);
  return { job, workPackages: workPackages.rows, categories: { estimates: ESTIMATE_CATEGORIES, otherActuals: OTHER_ACTUAL_CATEGORIES }, estimates: estimateRows, actuals: { suppliers: supplierRows, labor: laborRows, materials: materialRows, other: otherRows }, reconciliation, confirmation: costConfirmation, issues, summary: { approvedRevenue: revenue, estimatedTotal, supplierCommitted: committedSupplier, actualSupplier, actualLabor, actualMaterial, actualOther, actualTotal, estimatedMargin: revenue - estimatedTotal, actualMargin: marginReady ? revenue - actualTotal : null, actualMarginPercent: marginReady && revenue > 0 ? ((revenue - actualTotal) / revenue) * 100 : null, marginReady } };
}

export async function createCostEstimate(jobId, payload = {}, actor = {}) {
  const job = await requireJob(jobId); const category = ESTIMATE_CATEGORIES.includes(payload.category) ? payload.category : null; const description = text(payload.description); const amount = money(payload.amount, 'Estimated amount');
  if (!category || !description) throw Object.assign(new Error('Category and description are required.'), { status: 400 }); const workPackageId = await validateWorkPackage(job.id, payload.workPackageId);
  const result = await db.query(`INSERT INTO job_cost_estimates (ongoing_job_id,work_package_id,category,description,estimated_amount_aed,created_by_user_id) VALUES ($1::uuid,$2::uuid,$3,$4,$5,$6::uuid) RETURNING id`, [job.id,workPackageId,category,description,amount,actor?.userId||null]); await audit(actor,'create','job_cost_estimate',result.rows[0].id,`Added ${category} estimate: ${description}`,job.id); return result.rows[0];
}

export async function updateCostEstimate(jobId, estimateId, payload = {}, actor = {}) {
  const job = await requireJob(jobId); const current = await db.query(`SELECT * FROM job_cost_estimates WHERE id=$1::uuid AND ongoing_job_id=$2::uuid AND archived_at IS NULL`, [uuid(estimateId),job.id]); if (!current.rows.length) throw Object.assign(new Error('Cost estimate not found.'), { status: 404 });
  const row=current.rows[0]; const category=Object.hasOwn(payload,'category')?(ESTIMATE_CATEGORIES.includes(payload.category)?payload.category:null):row.category; const description=Object.hasOwn(payload,'description')?text(payload.description):row.description; const amount=Object.hasOwn(payload,'amount')?money(payload.amount,'Estimated amount'):Number(row.estimated_amount_aed); const workPackageId=Object.hasOwn(payload,'workPackageId')?await validateWorkPackage(job.id,payload.workPackageId):row.work_package_id;
  if(!category||!description) throw Object.assign(new Error('Category and description are required.'),{status:400}); await db.query(`UPDATE job_cost_estimates SET work_package_id=$3::uuid,category=$4,description=$5,estimated_amount_aed=$6,updated_at=NOW() WHERE id=$1::uuid AND ongoing_job_id=$2::uuid`,[row.id,job.id,workPackageId,category,description,amount]); await audit(actor,'update','job_cost_estimate',row.id,`Updated cost estimate: ${description}`,job.id); return {id:row.id};
}

export async function archiveCostEstimate(jobId, estimateId, actor = {}) { const job=await requireJob(jobId); const result=await db.query(`UPDATE job_cost_estimates SET archived_at=NOW(),updated_at=NOW() WHERE id=$1::uuid AND ongoing_job_id=$2::uuid AND archived_at IS NULL RETURNING id,description`,[uuid(estimateId),job.id]); if(!result.rows.length) throw Object.assign(new Error('Cost estimate not found.'),{status:404}); await audit(actor,'archive','job_cost_estimate',result.rows[0].id,`Archived cost estimate: ${result.rows[0].description}`,job.id); return {id:result.rows[0].id}; }

export async function createOtherActualCost(jobId, payload = {}, actor = {}) { const job=await requireJob(jobId); const category=OTHER_ACTUAL_CATEGORIES.includes(payload.category)?payload.category:null; const description=text(payload.description); const amount=money(payload.amount); if(!category||!description) throw Object.assign(new Error('Category and description are required.'),{status:400}); const workPackageId=await validateWorkPackage(job.id,payload.workPackageId); const result=await db.query(`INSERT INTO job_actual_costs (ongoing_job_id,work_package_id,category,description,amount_aed,reference,occurred_at,created_by_user_id) VALUES ($1::uuid,$2::uuid,$3,$4,$5,$6,$7,$8::uuid) RETURNING id`,[job.id,workPackageId,category,description,amount,text(payload.reference),timestamp(payload.occurredAt),actor?.userId||null]); await audit(actor,'create','job_actual_cost',result.rows[0].id,`Recorded ${category} actual cost: ${description}`,job.id); return result.rows[0]; }

export async function voidOtherActualCost(jobId, costId, payload = {}, actor = {}) { const job=await requireJob(jobId); const reason=text(payload.reason); if(!reason) throw Object.assign(new Error('A reason is required to void an actual cost.'),{status:400}); const result=await db.query(`UPDATE job_actual_costs SET voided_at=NOW(),voided_by_user_id=$3::uuid,void_reason=$4 WHERE id=$1::uuid AND ongoing_job_id=$2::uuid AND voided_at IS NULL RETURNING id,description`,[uuid(costId),job.id,actor?.userId||null,reason]); if(!result.rows.length) throw Object.assign(new Error('Actual cost not found.'),{status:404}); await audit(actor,'void','job_actual_cost',result.rows[0].id,`Voided actual cost: ${result.rows[0].description} — ${reason}`,job.id); return {id:result.rows[0].id}; }

export async function confirmJobCosts(jobId, payload = {}, actor = {}) { const job=await requireJob(jobId); const costing=await getJobCosting(job.id); const blockers=[]; if(costing.issues.supplierActualsMissing) blockers.push(`${costing.issues.supplierActualsMissing} supplier actual amount(s)`); if(costing.issues.laborRatesMissing) blockers.push(`${costing.issues.laborRatesMissing} time entry rate(s)`); if(costing.issues.materialPricesMissing) blockers.push(`${costing.issues.materialPricesMissing} material movement price(s)`); if(blockers.length) throw Object.assign(new Error(`Costs cannot be confirmed until these are complete: ${blockers.join(', ')}.`),{status:409}); await db.query(`INSERT INTO job_cost_confirmations (ongoing_job_id,confirmed_at,confirmed_by_user_id,confirmation_note,reopened_at,reopened_by_user_id,reopen_reason,updated_at) VALUES ($1::uuid,NOW(),$2::uuid,$3,NULL,NULL,NULL,NOW()) ON CONFLICT (ongoing_job_id) DO UPDATE SET confirmed_at=NOW(),confirmed_by_user_id=EXCLUDED.confirmed_by_user_id,confirmation_note=EXCLUDED.confirmation_note,reopened_at=NULL,reopened_by_user_id=NULL,reopen_reason=NULL,updated_at=NOW()`,[job.id,actor?.userId||null,text(payload.note)]); await audit(actor,'confirm','job_costing',job.id,'Confirmed all known Job costs are recorded',job.id); return {confirmed:true}; }

export async function reopenJobCosts(jobId, payload = {}, actor = {}) { const job=await requireJob(jobId); const reason=text(payload.reason); if(!reason) throw Object.assign(new Error('A reason is required to reopen costing.'),{status:400}); const result=await db.query(`UPDATE job_cost_confirmations SET reopened_at=NOW(),reopened_by_user_id=$2::uuid,reopen_reason=$3,updated_at=NOW() WHERE ongoing_job_id=$1::uuid AND reopened_at IS NULL RETURNING ongoing_job_id`,[job.id,actor?.userId||null,reason]); if(!result.rows.length) throw Object.assign(new Error('Job costs are not currently confirmed.'),{status:409}); await audit(actor,'reopen','job_costing',job.id,`Reopened Job costs: ${reason}`,job.id); return {confirmed:false}; }
