import db from '../db/index.js';

function date(value, fallback) { if (!value) return fallback; const result = new Date(value); return Number.isNaN(result.getTime()) ? fallback : result; }
function numeric(row, fields) { const result = { ...row }; fields.forEach((field) => { result[field] = Number(result[field] || 0); }); return result; }

export async function getOperationalReport({ from, to } = {}) {
  const end = date(to, new Date()); const start = date(from, new Date(end.getFullYear() - 1, end.getMonth(), end.getDate()));
  if (to) end.setHours(23, 59, 59, 999);
  if (from) start.setHours(0, 0, 0, 0);
  const liveJobs = `oj.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM migration_entity_map mem WHERE mem.target_table = 'ongoing_jobs' AND mem.target_entity_id = oj.id AND mem.source_collection = 'jobs')`;
  const [jobs, blockedActivities, overdueSuppliers, overdueSnags, upcomingInstallations, longTimers, lowStock, supplierPerformance, servicePerformance] = await Promise.all([
    db.query(`SELECT oj.id, oj.job_number AS "jobNumber", oj.title, oj.summary_stage AS stage, oj.value_aed AS "jobValue", oj.owner, oj.created_at AS "createdAt", oj.closed_at AS "closedAt",
      COALESCE(scope.count,0)::int AS "scopeCount", COALESCE(activity.count,0)::int AS "activityCount", COALESCE(activity.completed,0)::int AS "completedActivities", COALESCE(activity.blocked,0)::int AS "blockedActivities",
      COALESCE(resources.count,0)::int AS "resourceAssignments", COALESCE(time.minutes,0)::int AS "actualMinutes", COALESCE(time.labor_cost,0) AS "actualLaborCost",
      COALESCE(supplier.count,0)::int AS "supplierCommitments", COALESCE(supplier.committed,0) AS "supplierCommittedCost", COALESCE(supplier.actual,0) AS "supplierActualCost", COALESCE(supplier.actual_known,0)::int AS "supplierActualKnown",
      COALESCE(stock.count,0)::int AS "inventoryMovements", COALESCE(material.actual,0) AS "actualMaterialCost", COALESCE(material.unpriced,0)::int AS "unpricedMaterialMovements", COALESCE(other_cost.actual,0) AS "actualOtherCost",
      COALESCE(closeout.photos,0)::int AS "finalPhotoCount", COALESCE(closeout.open_snags,0)::int AS "openSnags", COALESCE(memory.learning,0)::int AS "learningCount",
      quote.amount AS "approvedQuoteAmount", COALESCE(release.exists, FALSE) AS "hasProductionRelease", COALESCE(cost_confirmation.confirmed,FALSE) AS "costsConfirmed"
      FROM ongoing_jobs oj
      LEFT JOIN LATERAL (SELECT COUNT(*) FROM job_scope_lines WHERE ongoing_job_id = oj.id AND archived_at IS NULL) scope ON TRUE
      LEFT JOIN LATERAL (SELECT COUNT(*) AS count, COUNT(*) FILTER (WHERE status='completed') AS completed, COUNT(*) FILTER (WHERE status='blocked' OR blocker IS NOT NULL) AS blocked FROM job_activities WHERE ongoing_job_id = oj.id AND archived_at IS NULL AND status <> 'cancelled') activity ON TRUE
      LEFT JOIN LATERAL (SELECT COUNT(*) FROM job_activity_resource_assignments a JOIN job_activities ja ON ja.id=a.job_activity_id WHERE ja.ongoing_job_id=oj.id AND ja.archived_at IS NULL) resources ON TRUE
      LEFT JOIN LATERAL (SELECT SUM(te.duration_minutes) AS minutes, SUM((te.duration_minutes/60.0)*COALESCE(r.hourly_cost_aed,0)) AS labor_cost FROM project_time_entries te JOIN operational_resources r ON r.id=te.resource_id WHERE te.ongoing_job_id=oj.id AND te.status='completed') time ON TRUE
      LEFT JOIN LATERAL (SELECT COUNT(*) FILTER (WHERE status<>'cancelled') AS count, SUM(committed_amount) FILTER (WHERE status<>'cancelled') AS committed, SUM(actual_amount) FILTER (WHERE status<>'cancelled') AS actual, COUNT(actual_amount) FILTER (WHERE status<>'cancelled') AS actual_known FROM supplier_commitments WHERE ongoing_job_id=oj.id) supplier ON TRUE
      LEFT JOIN LATERAL (SELECT COUNT(*) FROM inventory_movements WHERE ongoing_job_id=oj.id) stock ON TRUE
      LEFT JOIN LATERAL (SELECT SUM(quantity*unit_cost_aed) AS actual, COUNT(*) FILTER (WHERE unit_cost_aed IS NULL) AS unpriced FROM inventory_movements WHERE ongoing_job_id=oj.id AND movement_type IN ('consumption','damage','loss')) material ON TRUE
      LEFT JOIN LATERAL (SELECT SUM(amount_aed) AS actual FROM job_actual_costs WHERE ongoing_job_id=oj.id AND voided_at IS NULL) other_cost ON TRUE
      LEFT JOIN LATERAL (SELECT (SELECT COUNT(*) FROM job_closeout_evidence WHERE ongoing_job_id=oj.id AND evidence_type='final_photo') AS photos, (SELECT COUNT(*) FROM job_snags WHERE ongoing_job_id=oj.id AND status IN ('open','in_progress')) AS open_snags) closeout ON TRUE
      LEFT JOIN LATERAL (SELECT COUNT(*) FILTER (WHERE note_type='learning') AS learning FROM notes WHERE target_entity_type='ongoing_job' AND target_entity_id=oj.id AND archived_at IS NULL) memory ON TRUE
      LEFT JOIN LATERAL (SELECT qv.total_amount AS amount FROM artifact_decisions ad JOIN quote_versions qv ON qv.id=ad.quote_version_id WHERE ad.ongoing_job_id=oj.id AND ad.artifact_type='quotation' AND ad.decision='approved' ORDER BY ad.decided_at DESC LIMIT 1) quote ON TRUE
      LEFT JOIN LATERAL (SELECT TRUE AS exists FROM production_releases WHERE ongoing_job_id=oj.id AND status='active' LIMIT 1) release ON TRUE
      LEFT JOIN LATERAL (SELECT TRUE AS confirmed FROM job_cost_confirmations WHERE ongoing_job_id=oj.id AND reopened_at IS NULL LIMIT 1) cost_confirmation ON TRUE
      WHERE ${liveJobs} ORDER BY oj.updated_at DESC NULLS LAST`, []),
    db.query(`SELECT ja.id, ja.ongoing_job_id AS "jobId", oj.title AS "jobTitle", ja.title, ja.blocker, ja.planned_end AS "plannedEnd", u.name AS "ownerName" FROM job_activities ja JOIN ongoing_jobs oj ON oj.id=ja.ongoing_job_id LEFT JOIN users u ON u.id=ja.owner_user_id WHERE ${liveJobs} AND ja.archived_at IS NULL AND (ja.status='blocked' OR ja.blocker IS NOT NULL) ORDER BY ja.planned_end NULLS LAST`),
    db.query(`SELECT sc.id, sc.ongoing_job_id AS "jobId", oj.title AS "jobTitle", o.canonical_name AS "supplierName", sc.description, sc.expected_delivery_at AS "expectedDeliveryAt", sc.status FROM supplier_commitments sc JOIN ongoing_jobs oj ON oj.id=sc.ongoing_job_id JOIN supplier_profiles sp ON sp.id=sc.supplier_profile_id JOIN organizations o ON o.id=sp.organization_id WHERE ${liveJobs} AND sc.status NOT IN ('delivered','cancelled') AND sc.expected_delivery_at < NOW() ORDER BY sc.expected_delivery_at`),
    db.query(`SELECT s.id, s.ongoing_job_id AS "jobId", oj.title AS "jobTitle", s.title, s.severity, s.due_at AS "dueAt", u.name AS "ownerName" FROM job_snags s JOIN ongoing_jobs oj ON oj.id=s.ongoing_job_id LEFT JOIN users u ON u.id=s.owner_user_id WHERE ${liveJobs} AND s.status IN ('open','in_progress') AND s.due_at < NOW() ORDER BY s.due_at`),
    db.query(`SELECT ja.id, ja.ongoing_job_id AS "jobId", oj.title AS "jobTitle", ja.title, ja.planned_start AS "plannedStart", ja.planned_end AS "plannedEnd", u.name AS "ownerName" FROM job_activities ja JOIN ongoing_jobs oj ON oj.id=ja.ongoing_job_id LEFT JOIN users u ON u.id=ja.owner_user_id WHERE ${liveJobs} AND ja.archived_at IS NULL AND ja.status NOT IN ('completed','cancelled') AND ja.activity_type='installation' AND ja.planned_start BETWEEN NOW() AND NOW()+INTERVAL '7 days' ORDER BY ja.planned_start`),
    db.query(`SELECT te.id, te.ongoing_job_id AS "jobId", oj.title AS "jobTitle", r.name AS "resourceName", te.started_at AS "startedAt" FROM project_time_entries te JOIN ongoing_jobs oj ON oj.id=te.ongoing_job_id JOIN operational_resources r ON r.id=te.resource_id WHERE ${liveJobs} AND te.status='running' AND te.started_at < NOW()-INTERVAL '12 hours' ORDER BY te.started_at`),
    db.query(`WITH signed AS (SELECT inventory_item_id, quantity FROM inventory_movements WHERE to_location_id IS NOT NULL UNION ALL SELECT inventory_item_id, -quantity FROM inventory_movements WHERE from_location_id IS NOT NULL), balance AS (SELECT inventory_item_id, SUM(quantity) quantity FROM signed GROUP BY inventory_item_id) SELECT i.id, i.name, i.sku, COALESCE(b.quantity,0) AS quantity, i.reorder_level AS "reorderLevel" FROM inventory_items i LEFT JOIN balance b ON b.inventory_item_id=i.id WHERE i.status='active' AND i.reorder_level IS NOT NULL AND COALESCE(b.quantity,0)<=i.reorder_level ORDER BY COALESCE(b.quantity,0)-i.reorder_level`),
    db.query(`SELECT sp.id, o.canonical_name AS name, COALESCE(metrics.commitments,0)::int AS commitments, COALESCE(metrics.delivered,0)::int AS delivered, COALESCE(metrics.on_time,0)::int AS "onTime", COALESCE(metrics.actual_spend,0) AS "actualSpend", COALESCE(issue_metrics.issues,0)::int AS issues FROM supplier_profiles sp JOIN organizations o ON o.id=sp.organization_id LEFT JOIN LATERAL (SELECT COUNT(*) FILTER (WHERE status<>'cancelled') AS commitments, COUNT(*) FILTER (WHERE status='delivered') AS delivered, COUNT(*) FILTER (WHERE status='delivered' AND actual_delivery_at<=expected_delivery_at) AS on_time, SUM(actual_amount) FILTER (WHERE status<>'cancelled') AS actual_spend FROM supplier_commitments WHERE supplier_profile_id=sp.id) metrics ON TRUE LEFT JOIN LATERAL (SELECT COUNT(*) AS issues FROM supplier_commitment_updates scu JOIN supplier_commitments sc ON sc.id=scu.supplier_commitment_id WHERE sc.supplier_profile_id=sp.id AND scu.update_type='issue') issue_metrics ON TRUE ORDER BY commitments DESC,o.canonical_name`),
    db.query(`SELECT COALESCE(so.canonical_label,'Unclassified') AS service, COUNT(DISTINCT jsl.ongoing_job_id)::int AS jobs, COUNT(jsl.id)::int AS "workPackages" FROM job_scope_lines jsl JOIN ongoing_jobs oj ON oj.id=jsl.ongoing_job_id LEFT JOIN service_offerings so ON so.id=jsl.service_offering_id WHERE ${liveJobs} AND jsl.archived_at IS NULL GROUP BY COALESCE(so.canonical_label,'Unclassified') ORDER BY jobs DESC, service`),
  ]);
  const jobRows = jobs.rows.map((row) => numeric(row, ['jobValue','actualMinutes','actualLaborCost','supplierCommittedCost','supplierActualCost','actualMaterialCost','actualOtherCost','approvedQuoteAmount'])).map((row) => {
    const dimensions = [row.scopeCount > 0, row.activityCount > 0, row.hasProductionRelease, row.supplierCommitments === 0 || row.supplierActualKnown === row.supplierCommitments, row.resourceAssignments === 0 || row.actualMinutes > 0, row.stage !== 'Job Done' || row.finalPhotoCount > 0, row.stage !== 'Job Done' || row.costsConfirmed];
    const actualCost = row.supplierActualCost + row.actualLaborCost + row.actualMaterialCost + row.actualOtherCost;
    return { ...row, actualCost, actualMargin: row.costsConfirmed && row.approvedQuoteAmount > 0 ? row.approvedQuoteAmount - actualCost : null, coveragePercent: Math.round((dimensions.filter(Boolean).length / dimensions.length) * 100), supplierCostComplete: row.supplierCommitments === 0 || row.supplierActualKnown === row.supplierCommitments };
  });
  const activeJobs = jobRows.filter((row) => !['Job Done','Job Lost'].includes(row.stage)); const doneInRange = jobRows.filter((row) => row.stage === 'Job Done' && row.closedAt && new Date(row.closedAt) >= start && new Date(row.closedAt) <= end);
  const marginRows = doneInRange.filter((row)=>row.actualMargin != null);
  const summary = { activeJobs: activeJobs.length, doneJobs: doneInRange.length, blockedActivities: blockedActivities.rows.length, overdueSupplierCommitments: overdueSuppliers.rows.length, overdueSnags: overdueSnags.rows.length, upcomingInstallations: upcomingInstallations.rows.length, longRunningTimers: longTimers.rows.length, lowStockItems: lowStock.rows.length, averageCoverage: jobRows.length ? Math.round(jobRows.reduce((sum,row)=>sum+row.coveragePercent,0)/jobRows.length) : 0, approvedRevenue: doneInRange.reduce((sum,row)=>sum+row.approvedQuoteAmount,0), supplierActualCost: doneInRange.reduce((sum,row)=>sum+row.supplierActualCost,0), laborActualCost: doneInRange.reduce((sum,row)=>sum+row.actualLaborCost,0), materialActualCost: doneInRange.reduce((sum,row)=>sum+row.actualMaterialCost,0), otherActualCost: doneInRange.reduce((sum,row)=>sum+row.actualOtherCost,0), confirmedMargin: marginRows.reduce((sum,row)=>sum+row.actualMargin,0), trustworthyMarginJobs: marginRows.length };
  return { period: { from: start, to: end }, summary, jobs: jobRows, exceptions: { blockedActivities: blockedActivities.rows, overdueSuppliers: overdueSuppliers.rows, overdueSnags: overdueSnags.rows, upcomingInstallations: upcomingInstallations.rows, longTimers: longTimers.rows, lowStock: lowStock.rows.map((row)=>numeric(row,['quantity','reorderLevel'])) }, supplierPerformance: supplierPerformance.rows.map((row)=>numeric(row,['commitments','delivered','onTime','actualSpend','issues'])), servicePerformance: servicePerformance.rows.map((row)=>numeric(row,['jobs','workPackages'])) };
}
