import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CalendarDays, Check, CheckCircle2, ChevronLeft, ChevronRight, ClipboardCheck, MapPin, PackageCheck, Sparkles, Users } from 'lucide-react';
import { crmApiFetch } from '../../crmApi.js';
import { Modal } from '../ui/Modal.jsx';
import { Alert, Badge, LoadingState, cn } from '../ui/primitives.jsx';

const STEPS=['Context','Activities','Responsibility','Review'];
function today(){const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,10);}
function scheduled(template,target){if(!target)return null;const start=new Date(`${target}T08:00:00+04:00`);start.setUTCDate(start.getUTCDate()+Number(template.daysFromTarget||0));const end=new Date(start.getTime()+Number(template.durationHours||8)*3600000);return{start,end};}
function when(value){return value?new Date(value).toLocaleString('en-AE',{weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'Not scheduled';}
function dayLabel(days){if(days===0)return'Target day';if(days<0)return`${Math.abs(days)} day${days===-1?'':'s'} before`;return`${days} day${days===1?'':'s'} after`;}

export default function JobActivationModal({ongoingJobId,open,onClose,onCreated}){
  const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [step,setStep]=useState(0);
  const [targetDate,setTargetDate]=useState(today);const [workPackageId,setWorkPackageId]=useState('');const [newWorkTitle,setNewWorkTitle]=useState('');const [serviceOfferingId,setServiceOfferingId]=useState('');
  const [phaseId,setPhaseId]=useState('');const [newPhaseName,setNewPhaseName]=useState('Delivery');const [locationId,setLocationId]=useState('');const [newLocation,setNewLocation]=useState({name:'',address:'',city:''});
  const [selectedCodes,setSelectedCodes]=useState([]);const [ownerUserId,setOwnerUserId]=useState('');const [activityOwners,setActivityOwners]=useState({});const [resourceIds,setResourceIds]=useState([]);
  const base=`/api/admin/sales/ongoing-jobs/${encodeURIComponent(ongoingJobId)}/delivery/activation`;
  const load=useCallback(async()=>{if(!open)return;setLoading(true);setError('');try{const result=await crmApiFetch(base);setData(result);const firstWork=result.workPackages.length===1?result.workPackages[0]:null;setWorkPackageId(firstWork?.id||(!result.workPackages.length?'__new__':''));setLocationId(result.locations.length===1?result.locations[0].id:(!result.locations.length?'__new__':''));setPhaseId(result.phases.length===1?result.phases[0].id:(!result.phases.length?'__new__':''));setTargetDate(result.suggestedTargetDate||today());setActivityOwners({});const owner=result.users.find((user)=>user.name===result.job.owner)||null;setOwnerUserId(owner?.id||'');setResourceIds(owner?result.resources.filter((resource)=>resource.userId===owner.id).map((resource)=>resource.id):[]);const serviceCode=firstWork?.serviceCode;setSelectedCodes(result.templates.filter((template)=>!serviceCode||template.serviceCodes.includes(serviceCode)).map((template)=>template.code));}catch(err){setError(err.message||'Could not load delivery setup.');}finally{setLoading(false);}},[base,open]);
  useEffect(()=>{if(open){setStep(0);load();}},[open,load]);
  const chosenWork=data?.workPackages.find((item)=>item.id===workPackageId);const selected=useMemo(()=>(data?.templates||[]).filter((template)=>selectedCodes.includes(template.code)),[data?.templates,selectedCodes]);
  const schedule=useMemo(()=>selected.map((template)=>({...template,...scheduled(template,targetDate)})),[selected,targetDate]);
  const conflicts=useMemo(()=>{if(!resourceIds.length)return[];return schedule.flatMap((activity)=>(data?.resourceBookings||[]).filter((booking)=>resourceIds.includes(booking.resourceId)&&activity.start<new Date(booking.plannedEnd)&&new Date(booking.plannedStart)<activity.end).map((booking)=>({...booking,activityTitle:activity.title})));},[data?.resourceBookings,resourceIds,schedule]);
  const requiresLocation=selected.some((item)=>item.requiresLocation);const requiresWork=selected.some((item)=>item.requiresWorkPackage);
  function useSuggestions(){const code=workPackageId==='__new__'?(data?.services||[]).find((item)=>item.id===serviceOfferingId)?.code:chosenWork?.serviceCode;setSelectedCodes((data?.templates||[]).filter((template)=>!code||template.serviceCodes.includes(code)).map((template)=>template.code));}
  function toggle(code){setSelectedCodes((current)=>current.includes(code)?current.filter((item)=>item!==code):[...current,code]);}
  function toggleResource(id){setResourceIds((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);}
  function setActivityOwner(code,id){setActivityOwners((current)=>({...current,[code]:id}));}
  function validate(nextStep){setError('');if(nextStep>0&&!targetDate){setError('Choose the main delivery or installation date.');return false;}if(nextStep>1&&!selected.length){setError('Choose at least one activity.');return false;}if(nextStep>2){if(!ownerUserId){setError('Choose the accountable owner.');return false;}if(requiresWork&&workPackageId==='__new__'&&!newWorkTitle.trim()){setError('Add a work package name for the selected activities.');return false;}if(requiresWork&&!workPackageId){setError('Choose a work package.');return false;}if(requiresLocation&&locationId==='__new__'&&!newLocation.name.trim()){setError('Add the delivery or installation location.');return false;}if(requiresLocation&&!locationId){setError('Choose a Job location.');return false;}}return true;}
  function next(){const nextStep=Math.min(3,step+1);if(validate(nextStep))setStep(nextStep);}
  async function activate(){if(!validate(3))return;setBusy(true);setError('');try{const result=await crmApiFetch(base,{method:'POST',body:JSON.stringify({targetDate,workPackageId:workPackageId&&workPackageId!=='__new__'?workPackageId:null,newWorkPackage:workPackageId==='__new__'?{title:newWorkTitle,serviceOfferingId:serviceOfferingId||null}:null,phaseId:phaseId&&phaseId!=='__new__'?phaseId:null,newPhaseName:phaseId==='__new__'?newPhaseName:null,locationId:locationId&&locationId!=='__new__'?locationId:null,newLocation:locationId==='__new__'?newLocation:null,ownerUserId,resourceIds,activities:selected.map((item)=>({templateId:item.id,title:item.title,ownerUserId:activityOwners[item.code]||null}))})});await onCreated?.(result);onClose();}catch(err){setError(err.message||'Could not activate the delivery plan.');}finally{setBusy(false);}}
  return <Modal open={open} onClose={onClose} title="Prepare for Delivery" subtitle="Turn the known Job scope into dated, assigned operational work." size="xl">
    {loading?<LoadingState label="Loading delivery setup…"/>:<div>
      {error&&<Alert>{error}</Alert>}
      <div className="mb-5 grid grid-cols-4 gap-1">{STEPS.map((label,index)=><div key={label} className={cn('rounded-lg px-2 py-2 text-center text-2xs font-semibold',index===step?'bg-brand text-white':index<step?'bg-emerald-50 text-emerald-700':'bg-neutral-100 text-neutral-400')}>{index<step?<Check className="mr-1 inline h-3 w-3"/>:null}{label}</div>)}</div>
      {data.activities.length>0&&<div className="mb-4 rounded-lg border border-sky-200 bg-sky-50 px-3 py-2 text-2xs text-sky-800">This Job already has {data.activities.length} active activit{data.activities.length===1?'y':'ies'}{data.activations.length?` from ${data.activations.length} prior activation${data.activations.length===1?'':'s'}`:''}. This workflow adds another package/location plan; it never replaces existing work.</div>}

      {step===0&&<div className="space-y-5">{(!data.readiness.hasBrief||!data.readiness.hasProductionRelease)&&<Alert tone="warning">Advisory: {!data.readiness.hasBrief?'the current Brief is missing':''}{!data.readiness.hasBrief&&!data.readiness.hasProductionRelease?' and ':''}{!data.readiness.hasProductionRelease?'no exact production release is active':''}. You may still prepare the plan, but production readiness will continue to show these gaps.</Alert>}<section className="rounded-xl border border-neutral-200 p-4"><div className="flex items-start gap-3"><CalendarDays className="mt-0.5 h-5 w-5 text-brand"/><div><h3 className="text-sm font-semibold">Main delivery / installation date</h3><p className="text-xs text-neutral-500">Activity dates are suggested backwards and forwards from this date. They remain draggable in the Plan Calendar.</p></div></div><input type="date" className="crm-input mt-3 w-full sm:w-52" value={targetDate} onChange={(event)=>setTargetDate(event.target.value)}/></section>
        <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-xl border border-neutral-200 p-4"><h3 className="flex items-center gap-2 text-xs font-semibold"><PackageCheck className="h-4 w-4 text-brand"/>Work package</h3><select className="crm-select mt-3 text-xs" value={workPackageId} onChange={(event)=>setWorkPackageId(event.target.value)}><option value="">Choose later</option>{data.workPackages.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}<option value="__new__">+ Create one now</option></select>{workPackageId==='__new__'&&<div className="mt-2 space-y-2"><input className="crm-input text-xs" value={newWorkTitle} onChange={(event)=>setNewWorkTitle(event.target.value)} placeholder="Deliverable name"/><select className="crm-select text-xs" value={serviceOfferingId} onChange={(event)=>setServiceOfferingId(event.target.value)}><option value="">Service optional</option>{data.services.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></div>}</section>
          <section className="rounded-xl border border-neutral-200 p-4"><h3 className="flex items-center gap-2 text-xs font-semibold"><MapPin className="h-4 w-4 text-brand"/>Location</h3><select className="crm-select mt-3 text-xs" value={locationId} onChange={(event)=>setLocationId(event.target.value)}><option value="">Choose later</option>{data.locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}<option value="__new__">+ Create one now</option></select>{locationId==='__new__'&&<div className="mt-2 space-y-2"><input className="crm-input text-xs" value={newLocation.name} onChange={(event)=>setNewLocation((value)=>({...value,name:event.target.value}))} placeholder="Site / venue name"/><input className="crm-input text-xs" value={newLocation.city} onChange={(event)=>setNewLocation((value)=>({...value,city:event.target.value}))} placeholder="City"/><input className="crm-input text-xs" value={newLocation.address} onChange={(event)=>setNewLocation((value)=>({...value,address:event.target.value}))} placeholder="Address / access note"/></div>}</section>
          <section className="rounded-xl border border-neutral-200 p-4"><h3 className="flex items-center gap-2 text-xs font-semibold"><ClipboardCheck className="h-4 w-4 text-brand"/>Phase</h3><select className="crm-select mt-3 text-xs" value={phaseId} onChange={(event)=>setPhaseId(event.target.value)}><option value="">No phase yet</option>{data.phases.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}<option value="__new__">+ Create one now</option></select>{phaseId==='__new__'&&<input className="crm-input mt-2 text-xs" value={newPhaseName} onChange={(event)=>setNewPhaseName(event.target.value)} placeholder="Phase name"/>}</section></div></div>}

      {step===1&&<div><div className="mb-3 flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">Choose the work that applies</h3><p className="text-xs text-neutral-500">These are removable building blocks, not a rigid service workflow.</p></div><button className="crm-btn-secondary shrink-0 text-xs" onClick={useSuggestions}><Sparkles className="h-3.5 w-3.5"/>Use suggestions</button></div><div className="grid gap-2 sm:grid-cols-2">{data.templates.map((template)=>{const checked=selectedCodes.includes(template.code);const relevant=!chosenWork?.serviceCode||template.serviceCodes.includes(chosenWork.serviceCode);return <button type="button" key={template.id} onClick={()=>toggle(template.code)} className={cn('rounded-xl border p-3 text-left transition',checked?'border-brand bg-brand-soft/40':'border-neutral-200 bg-white hover:border-neutral-300')}><div className="flex items-start gap-3"><span className={cn('mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded border',checked?'border-brand bg-brand text-white':'border-neutral-300')}>{checked&&<Check className="h-3.5 w-3.5"/>}</span><div><div className="flex flex-wrap items-center gap-2"><strong className="text-xs">{template.title}</strong>{relevant&&<Badge tone="info">Suggested</Badge>}</div><p className="mt-1 text-2xs leading-4 text-neutral-500">{template.description}</p><p className="mt-1 text-2xs font-medium text-neutral-400">{dayLabel(template.daysFromTarget)} · {template.durationHours} planned hours</p></div></div></button>;})}</div></div>}

      {step===2&&<div className="space-y-5"><section className="rounded-xl border border-neutral-200 p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><Users className="h-4 w-4 text-brand"/>Default activity owner</h3><p className="mt-1 text-xs text-neutral-500">The Job keeps its main leader. Choose a fast default here, then override any activity that belongs to someone else.</p><select className="crm-select mt-3 w-full text-xs sm:w-80" value={ownerUserId} onChange={(event)=>{const id=event.target.value;setOwnerUserId(id);setResourceIds(data.resources.filter((resource)=>resource.userId===id).map((resource)=>resource.id));}}><option value="">Choose owner…</option>{data.users.map((user)=><option key={user.id} value={user.id}>{user.name}{user.role?` · ${user.role}`:''}</option>)}</select><div className="mt-4 grid gap-2 sm:grid-cols-2">{selected.map((activity)=><label key={activity.id} className="rounded-lg bg-neutral-50 p-3 text-xs"><span className="font-semibold text-neutral-800">{activity.title}</span><select className="crm-select mt-2 text-xs" value={activityOwners[activity.code]||''} onChange={(event)=>setActivityOwner(activity.code,event.target.value)}><option value="">Use default owner</option>{data.users.map((user)=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label>)}</div></section><section className="rounded-xl border border-neutral-200 p-4"><h3 className="text-sm font-semibold">Crew, vehicles and equipment</h3><p className="mt-1 text-xs text-neutral-500">Optional. Selected resources are reserved on every activity now and can be refined per activity later.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.resources.map((resource)=><button type="button" key={resource.id} onClick={()=>toggleResource(resource.id)} className={cn('rounded-lg border px-3 py-2 text-left',resourceIds.includes(resource.id)?'border-brand bg-brand-soft/40':'border-neutral-200')}><strong className="text-xs">{resource.name}</strong><p className="text-2xs capitalize text-neutral-400">{resource.resourceType.replaceAll('_',' ')}</p></button>)}</div></section>{conflicts.length>0&&<Alert tone="warning"><strong>{conflicts.length} possible resource conflict{conflicts.length===1?'':'s'}.</strong> Review the clashes on the next step; activation is allowed because urgent EGS work may intentionally overlap.</Alert>}</div>}

      {step===3&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-neutral-950 p-4 text-white"><p className="text-2xs uppercase text-white/50">Target</p><p className="mt-1 text-sm font-semibold">{new Date(`${targetDate}T12:00:00`).toLocaleDateString('en-AE',{day:'numeric',month:'short',year:'numeric'})}</p></div><div className="rounded-xl bg-neutral-100 p-4"><p className="text-2xs uppercase text-neutral-400">Activities</p><p className="mt-1 text-2xl font-bold">{selected.length}</p></div><div className="rounded-xl bg-neutral-100 p-4"><p className="text-2xs uppercase text-neutral-400">Resources</p><p className="mt-1 text-2xl font-bold">{resourceIds.length}</p></div></div><section className="overflow-hidden rounded-xl border border-neutral-200"><div className="border-b border-neutral-200 bg-neutral-50 px-4 py-3"><h3 className="text-xs font-semibold">Proposed schedule</h3></div><div className="divide-y divide-neutral-100">{schedule.map((item)=>{const owner=data.users.find((user)=>user.id===(activityOwners[item.code]||ownerUserId));return <div key={item.id} className="flex items-center justify-between gap-3 px-4 py-3"><div><strong className="text-xs">{item.title}</strong><p className="text-2xs text-neutral-400">{item.activityType.replaceAll('_',' ')} · {item.durationHours} h · {owner?.name||'Unassigned'}</p></div><span className="text-right text-2xs font-medium text-neutral-600">{when(item.start)}<br/>to {when(item.end)}</span></div>;})}</div></section>{conflicts.length>0&&<section className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="flex items-center gap-2 text-xs font-semibold text-amber-800"><AlertTriangle className="h-4 w-4"/>Advisory resource conflicts</h3><div className="mt-2 space-y-1">{conflicts.slice(0,8).map((item,index)=><p key={`${item.resourceId}-${index}`} className="text-2xs text-amber-800"><strong>{item.resourceName}</strong>: {item.activityTitle} overlaps {item.title} on {item.jobTitle}.</p>)}</div></section>}<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-800"><CheckCircle2 className="mr-2 inline h-4 w-4"/>Activation writes normal Job activities. Calendar, Today, Production, resource planning and Job Memory will use the same records immediately.</div></div>}

      <div className="mt-6 flex items-center justify-between border-t border-neutral-200 pt-4"><button className="crm-btn-secondary" disabled={step===0||busy} onClick={()=>{setError('');setStep((value)=>Math.max(0,value-1));}}><ChevronLeft className="h-4 w-4"/>Back</button>{step<3?<button className="crm-btn-primary" onClick={next}>Continue<ChevronRight className="h-4 w-4"/></button>:<button className="crm-btn-primary" disabled={busy} onClick={activate}><Sparkles className="h-4 w-4"/>{busy?'Activating…':`Activate ${selected.length} activities`}</button>}</div>
    </div>}
  </Modal>;
}
