import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Camera, CheckCircle2, ClipboardCheck, Lightbulb, Plus, Upload } from 'lucide-react';
import { crmApiFetch, normalizeId } from '../../crmApi.js';
import { getMediaUrl } from '../../utils/mediaUrl.js';
import { Alert, Badge, EmptyState, LoadingState } from '../ui/primitives.jsx';

const EVIDENCE_LABELS = { final_photo: 'Final delivery photo', before_photo: 'Before photo', installation_photo: 'Installation photo', handover_document: 'Handover document', snag_photo: 'Snag photo', other: 'Other evidence' };
const STATUS_LABELS = { open: 'Open', in_progress: 'In progress', resolved: 'Resolved', accepted: 'Accepted' };
function localInput(value) { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function when(value) { return value ? new Date(value).toLocaleString('en-AE', { day: 'numeric', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit' }) : '—'; }

export default function JobCloseoutPanel({ ongoingJobId, contacts = [], active = true, onChanged }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [evidence, setEvidence] = useState({ type: 'final_photo', title: '', capturedAt: '' }); const [files, setFiles] = useState([]); const [fileKey, setFileKey] = useState(0);
  const [handover, setHandover] = useState({ handoverAt: '', handoverContactPersonId: '', handoverNote: '', completionSummary: '' });
  const [snag, setSnag] = useState({ title: '', description: '', severity: 'normal', ownerUserId: '', workPackageId: '', locationId: '', dueAt: '' }); const [resolutions, setResolutions] = useState({}); const [learning, setLearning] = useState('');
  const base = `/api/admin/sales/ongoing-jobs/${encodeURIComponent(ongoingJobId)}/closeout`;
  const load = useCallback(async () => { try { setError(''); const result = await crmApiFetch(base); setData(result); setHandover({ handoverAt: localInput(result.closeout?.handoverAt), handoverContactPersonId: result.closeout?.handoverContactPersonId || '', handoverNote: result.closeout?.handoverNote || '', completionSummary: result.closeout?.completionSummary || '' }); } catch (err) { setError(err.message || 'Failed to load closeout.'); } finally { setLoading(false); } }, [base]); useEffect(() => { if (active) { setLoading(true); load(); } }, [active, load]);
  async function json(path, method, payload, reset) { setBusy(true); setError(''); try { await crmApiFetch(`${base}${path}`, { method, body: JSON.stringify(payload) }); reset?.(); await load(); onChanged?.(); } catch (err) { setError(err.message || 'Could not save closeout record.'); } finally { setBusy(false); } }
  async function upload(event) { event.preventDefault(); if (!files.length) return; setBusy(true); setError(''); try { const body = new FormData(); body.append('type', evidence.type); body.append('title', evidence.title); body.append('capturedAt', evidence.capturedAt); files.forEach((file) => body.append('files', file)); await crmApiFetch(`${base}/evidence`, { method: 'POST', body }); setFiles([]); setFileKey((value) => value + 1); setEvidence((value) => ({ ...value, title: '', capturedAt: '' })); await load(); onChanged?.(); } catch (err) { setError(err.message || 'Could not upload closeout evidence.'); } finally { setBusy(false); } }
  async function addLearning(event) { event.preventDefault(); if (!learning.trim()) return; setBusy(true); try { const body = new FormData(); body.append('type', 'learning'); body.append('content', learning); body.append('pinned', 'false'); await crmApiFetch(`/api/admin/sales/ongoing-jobs/${encodeURIComponent(ongoingJobId)}/memory`, { method: 'POST', body }); setLearning(''); onChanged?.(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading Job closeout…" />;
  return <div className="space-y-5">{error && <Alert>{error}</Alert>}
    <section className="rounded-xl border border-neutral-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-brand" /><h3 className="text-sm font-semibold">Closeout readiness</h3></div><p className="mt-1 text-xs text-neutral-500">A Final delivery photo is mandatory before this Job can move to Job Done.</p></div><Badge tone={data.readiness.readyForJobDone ? 'success' : 'warning'}>{data.readiness.readyForJobDone ? 'Photo requirement complete' : 'Final photo required'}</Badge></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className={`rounded-lg p-3 text-xs ${data.readiness.finalPhotoReady ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{data.readiness.finalPhotoReady ? <CheckCircle2 className="mb-2 h-4 w-4" /> : <Camera className="mb-2 h-4 w-4" />}<strong>{data.readiness.finalPhotoCount} final photo{data.readiness.finalPhotoCount === 1 ? '' : 's'}</strong><p className="mt-1">At least one is required.</p></div><div className={`rounded-lg p-3 text-xs ${data.readiness.handoverReady ? 'bg-emerald-50 text-emerald-800' : 'bg-neutral-50 text-neutral-600'}`}><ClipboardCheck className="mb-2 h-4 w-4" /><strong>{data.readiness.handoverReady ? 'Handover recorded' : 'Handover not recorded'}</strong><p className="mt-1">Operational evidence, currently advisory.</p></div></div></section>
    <section className="rounded-xl border border-neutral-200 bg-white p-4"><div className="flex items-center gap-2"><Camera className="h-4 w-4 text-brand" /><h3 className="text-sm font-semibold">Photos and handover evidence</h3></div><form className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4" onSubmit={upload}><select className="crm-select text-xs" value={evidence.type} onChange={(e) => setEvidence((v) => ({ ...v, type: e.target.value }))}>{data.evidenceTypes.map((type) => <option key={type} value={type}>{EVIDENCE_LABELS[type]}</option>)}</select><input className="crm-input text-xs" value={evidence.title} onChange={(e) => setEvidence((v) => ({ ...v, title: e.target.value }))} placeholder="Short label or viewpoint" /><label className="text-2xs text-neutral-500">Captured at<input type="datetime-local" className="crm-input mt-1 text-xs" value={evidence.capturedAt} onChange={(e) => setEvidence((v) => ({ ...v, capturedAt: e.target.value }))} /></label><label className="crm-btn-secondary cursor-pointer self-end"><Upload className="h-4 w-4" />{files.length ? `${files.length} selected` : 'Select files'}<input key={fileKey} type="file" multiple accept={evidence.type === 'final_photo' ? 'image/*' : 'image/*,.pdf'} capture={evidence.type === 'final_photo' ? 'environment' : undefined} className="sr-only" onChange={(e) => setFiles(Array.from(e.target.files || []))} /></label><button className="crm-btn-primary lg:col-start-4" disabled={busy || !files.length}><Upload className="h-4 w-4" />Upload evidence</button></form>{data.evidence.length > 0 ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.evidence.map((item) => <a key={item.id} href={getMediaUrl(item.url)} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border border-neutral-200 hover:border-brand/40">{item.mimeType?.startsWith('image/') ? <img src={getMediaUrl(item.url)} alt={item.title || item.fileName} className="aspect-video w-full object-cover" /> : <div className="flex aspect-video items-center justify-center bg-neutral-50 text-xs text-neutral-400">Document</div>}<div className="p-2.5"><Badge tone={item.type === 'final_photo' ? 'success' : 'neutral'}>{EVIDENCE_LABELS[item.type]}</Badge><p className="mt-2 truncate text-2xs font-medium">{item.title || item.fileName}</p><p className="mt-1 text-2xs text-neutral-400">{item.uploadedBy} · {when(item.createdAt)}</p></div></a>)}</div> : <div className="mt-4"><EmptyState title="No closeout evidence" description="Upload the finished work from site before marking the Job Done." /></div>}</section>
    <section className="rounded-xl border border-neutral-200 bg-white p-4"><h3 className="text-sm font-semibold">Physical handover</h3><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); json('/handover', 'PATCH', handover); }}><label className="text-xs font-medium text-neutral-600">Handover date and time<input type="datetime-local" className="crm-input mt-1.5 w-full" value={handover.handoverAt} onChange={(e) => setHandover((v) => ({ ...v, handoverAt: e.target.value }))} /></label><label className="text-xs font-medium text-neutral-600">Client contact<select className="crm-select mt-1.5 w-full" value={handover.handoverContactPersonId} onChange={(e) => setHandover((v) => ({ ...v, handoverContactPersonId: e.target.value }))}><option value="">Not recorded</option>{contacts.map((contact) => <option key={normalizeId(contact._id)} value={normalizeId(contact._id)}>{contact.name || contact.email}</option>)}</select></label><label className="text-xs font-medium text-neutral-600">Handover note<textarea className="crm-input mt-1.5 min-h-20 w-full resize-y" value={handover.handoverNote} onChange={(e) => setHandover((v) => ({ ...v, handoverNote: e.target.value }))} placeholder="Who accepted it, and were any exceptions noted?" /></label><label className="text-xs font-medium text-neutral-600">Completion summary<textarea className="crm-input mt-1.5 min-h-20 w-full resize-y" value={handover.completionSummary} onChange={(e) => setHandover((v) => ({ ...v, completionSummary: e.target.value }))} placeholder="What EGS physically delivered" /></label><button className="crm-btn-primary sm:col-start-2" disabled={busy}>Save handover</button></form></section>
  </div>;
}
